# NATS Server Configuration

# Client port of 4222 on all interfaces
port:4222

# HTTP monitoring port
monitor_port: 8222

# 启用 JetStream
jetstream {
	# Specify a directory to persist the data
  store_dir: /data/jetstream
  # Optional: Limit the memory used by JetStream
  # max_memory: 1GB
  # Optional: Limit the disk space used by JetStream
  # max_storage: 10GB
}
