syntax = "proto3";

package api.v1.services.message;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "types/system.proto";
import "validate/validate.proto";

option go_package = "origadmin/application/admin/api/v1/services/message;message";
option java_multiple_files = true;
option java_outer_classname = "APIV1ServicesMessageMessageProto";
option java_package = "com.origadmin.api.v1.services.message";

// MessageService is the message service definition
service MessageService {
  // StreamRules
  rpc StreamMessage(StreamMessageRequest) returns (stream StreamMessageResponse) {}
}

message StreamMessageRequest {
  string message = 1 [json_name = "message"];
}

message StreamMessageResponse {
  string message = 1 [json_name = "message"];
}
