syntax = "proto3";

package api.v1.services.types;

import "errors/errors.proto";

option go_package = "origadmin/application/admin/api/v1/services/types;types";
option java_multiple_files = true;
option java_outer_classname = "APIServiceTypeAuthErrorProto";
option java_package = "com.origadmin.api.v1.services.types";
option objc_class_prefix = "APIServiceType";

enum AuthErrorReason {
  option (errors.default_code) = 500;
  AUTH_ERROR_REASON_UNSPECIFIED = 0;
  AUTH_ERROR_REASON_CAPTCHA_NOT_FOUND = 2001 [(errors.code) = 404];
  AUTH_ERROR_REASON_TOKEN_EXPIRED = 2002 [(errors.code) = 401];
}
