syntax = "proto3";

package api.v1.services.types;

import "google/protobuf/timestamp.proto";

option go_package = "origadmin/application/admin/api/v1/services/types;types";
option java_multiple_files = true;
option java_outer_classname = "APIServiceTypeSystemProto";
option java_package = "com.origadmin.api.v1.services.types";
option objc_class_prefix = "APIServiceType";

// View is the model entity for the View schema.
message View {
  // ID of the ent.
  int64 id = 1 [json_name = "id"];
  // CreateTime holds the value of the "create_time" field.
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // UpdateTime holds the value of the "update_time" field.
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // Code holds the value of the "keyword" field.
  string keyword = 4 [json_name = "keyword"];
  // Name holds the value of the "name" field.
  string name = 5 [json_name = "name"];
  // Scope holds the value of the "scope" field.
  string scope = 6 [json_name = "scope"];
  // I18nKey holds the value of the "i18n_key" field.
  string i18n_key = 7 [json_name = "i18n_key"];
  // Description holds the value of the "description" field.
  string description = 8 [json_name = "description"];
  // Sequence holds the value of the "sequence" field.
  int32 sequence = 9 [json_name = "sequence"];
  // Type holds the value of the "type" field.
  string type = 10 [json_name = "type"];
  // Component holds the value of the "component" field.
  string component = 11 [json_name = "component"];
  // Comment holds the value of the "comment" field.
  string comment = 12 [json_name = "comment"];
  // Icon holds the value of the "icon" field.
  string icon = 13 [json_name = "icon"];
  // Visible holds the value of the "visible" field.
  bool visible = 14 [json_name = "visible"];
  // Path holds the value of the "path" field.
  string path = 15 [json_name = "path"];
  // TreePath holds the value of the "tree_path" field.
  string tree_path = 16 [json_name = "tree_path"];
  // Properties holds the value of the "properties" field.
  string properties = 17 [json_name = "properties"];
  // Status holds the value of the "status" field.
  int32 status = 18 [json_name = "status"];
  // ParentID holds the value of the "parent_id" field.
  int64 parent_id = 19 [json_name = "parent_id"];
  // ParentPath holds the value of the "parent_path" field.
  string parent_path = 20 [json_name = "parent_path"];
  // Children holds the value of the children edge.
  repeated View children = 21 [json_name = "children"];
  // Parent holds the value of the parent edge.
  View parent = 22 [json_name = "parent"];
  // Resources holds the value of the resources edge.
  repeated Resource resources = 23 [json_name = "resources"];
  // Roles holds the value of the roles edge.
  repeated Role roles = 24 [json_name = "roles"];
}

// Role is the model entity for the Role schema.
message Role {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // role.field.keyword
  string keyword = 6 [json_name = "keyword"];
  // role.field.name
  string name = 7 [json_name = "name"];
  // role.field.description
  string description = 8 [json_name = "description"];
  // role.field.type
  int32 type = 9 [json_name = "type"];
  // role.field.sequence
  int32 sequence = 10 [json_name = "sequence"];
  // role.field.status
  int32 status = 11 [json_name = "status"];
  // role.field.is_types
  bool is_types = 12 [json_name = "is_types"];
  // Views holds the value of the views edge.
  repeated View views = 21 [json_name = "views"];
  // View Ids holds the value of the view_ids edge.
  repeated int64 view_ids = 20 [json_name = "view_ids"];
  // Users holds the value of the users edge.
  repeated User users = 22 [json_name = "users"];
  // Users Ids holds the value of the user_ids edge.
  repeated int64 user_ids = 23 [json_name = "user_ids"];
  // Resources holds the value of the resources edge.
  repeated Resource resources = 24 [json_name = "resources"];
  // Resource Ids holds the value of the resource_ids edge.
  repeated int64 resource_ids = 25 [json_name = "resource_ids"];
  // Permissions holds the value of the permissions edge.
  repeated Permission permissions = 26 [json_name = "permissions"];
  // Permission Ids holds the value of the permission_ids edge.
  repeated int64 permission_ids = 27 [json_name = "permission_ids"];
}

// User is the model entity for the User schema.
message User {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // user.field.uuid
  string uuid = 6 [json_name = "uuid"];
  // user.field.allowed_ip
  string allowed_ip = 7 [json_name = "allowed_ip"];
  // user.field.username
  string username = 8 [json_name = "username"];
  // user.field.nickname
  string nickname = 9 [json_name = "nickname"];
  // user.field.avatar
  string avatar = 10 [json_name = "avatar"];
  // user.field.nickname
  string name = 11 [json_name = "name"];
  // user.field.gender
  string gender = 12 [json_name = "gender"];
  // user.field.phone
  string phone = 13 [json_name = "phone"];
  // user.field.email
  string email = 14 [json_name = "email"];
  // user.field.remark
  string remark = 15 [json_name = "remark"];
  // user.field.token
  string token = 16 [json_name = "token"];
  // user.field.status
  int32 status = 17 [json_name = "status"];
  // user.field.i18n
  string i18n = 18 [json_name = "i18n"];
  // user.field.last_login_ip
  string last_login_ip = 19 [json_name = "last_login_ip"];
  // user.field.login_ip
  string login_ip = 20 [json_name = "login_ip"];
  // user.field.last_login_time
  google.protobuf.Timestamp last_login_time = 21 [json_name = "last_login_time"];
  // user.field.login_time
  google.protobuf.Timestamp login_time = 22 [json_name = "login_time"];
  // user.field.sanction_date
  optional google.protobuf.Timestamp sanction_date = 23 [json_name = "sanction_date"];
  // Roles holds the value of the roles edge.
  repeated Role roles = 24 [json_name = "roles"];
  // Role Ids holds the value of the role_ids
  repeated int64 role_ids = 25 [json_name = "role_ids"];
}

// UserRole is the model entity for the UserRole schema.
message UserRole {
  // ID of the ent.
  int64 id = 1 [json_name = "id"];
  // CreateTime holds the value of the "create_time" field.
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // UpdateTime holds the value of the "update_time" field.
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // UserID holds the value of the "user_id" field.
  int64 user_id = 4 [json_name = "user_id"];
  // RoleID holds the value of the "role_id" field.
  int64 role_id = 5 [json_name = "role_id"];
  // RoleName holds the value of the "role_name" field.
  string role_name = 6 [json_name = "role_name"];
  // User holds the value of the user edge.
  User user = 21 [json_name = "user"];
  // Role holds the value of the role edge.
  Role role = 22 [json_name = "role"];
}

// RoleView is the model entity for the RoleView schema.
message RoleView {
  // ID of the ent.
  int64 id = 1 [json_name = "id"];
  // CreateTime holds the value of the "create_time" field.
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // UpdateTime holds the value of the "update_time" field.
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // RoleID holds the value of the "role_id" field.
  int64 role_id = 4 [json_name = "role_id"];
  // ViewID holds the value of the "view_id" field.
  int64 view_id = 5 [json_name = "view_id"];
  // Role holds the value of the role edge.
  Role role = 21 [json_name = "role"];
  // View holds the value of the view edge.
  View view = 22 [json_name = "view"];
}

// Resource is the model entity for the Resource schema.
message Resource {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // resource.field.name
  string name = 6 [json_name = "name"];
  // resource.field.keyword
  string keyword = 7 [json_name = "keyword"];
  // resource.field.type
  string type = 9 [json_name = "type"];
  // resource.field.status
  int32 status = 10 [json_name = "status"];
  // resource.field.path
  string path = 11 [json_name = "path"];
  // resource.field.operation
  string operation = 12 [json_name = "operation"];
  // resource.field.method
  string method = 13 [json_name = "method"];
  // resource.field.sequence
  int32 sequence = 14 [json_name = "sequence"];
  // resource.field.tree_path
  string tree_path = 16 [json_name = "tree_path"];
  // resource.field.properties
  map<string, string> properties = 17 [json_name = "properties"];
  // resource.field.description
  string description = 18 [json_name = "description"];
  // resource.field.parent_id
  int64 parent_id = 19 [json_name = "parent_id"];
  // Children holds the value of the children edge.
  repeated Resource children = 21 [json_name = "children"];
  // Parent holds the value of the parent edge.
  Resource parent = 22 [json_name = "parent"];
  // Permission Ids holds the value of the permission_ids edge.
  repeated int64 permission_ids = 23 [json_name = "permission_ids"];
  // Permissions holds the value of the permissions edge.
  repeated Permission permissions = 24 [json_name = "permissions"];

  string service_name = 25 [json_name = "service_name"];
}

// department.table.comment
message Department {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // department.field.keyword
  string keyword = 6 [json_name = "keyword"];
  // department.field.name
  string name = 7 [json_name = "name"];
  // department.field.tree_path
  string tree_path = 8 [json_name = "tree_path"];
  // department.field.sequence
  int32 sequence = 9 [json_name = "sequence"];
  // department.field.status
  int32 status = 10 [json_name = "status"];
  // department.field.level
  int32 level = 11 [json_name = "level"];
  // department.field.description
  string description = 12 [json_name = "description"];
  // department.field.parent_id
  int64 parent_id = 13 [json_name = "parent_id"];
  // Children holds the value of the children edge.
  repeated Department children = 14 [json_name = "children"];
  // Parent holds the value of the parent edge.
  Department parent = 15 [json_name = "parent"];
}

// user_department.table.comment
message UserDepartment {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // field.foreign_key.comment
  int64 user_id = 2 [json_name = "user_id"];
  // field.foreign_key.comment
  int64 department_id = 3 [json_name = "department_id"];
}

// position.table.comment
message Position {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // position.field.name
  string name = 6 [json_name = "name"];
  // position.field.keyword
  string keyword = 7 [json_name = "keyword"];
  // position.field.description
  string description = 8 [json_name = "description"];
  // department.field.department_id
  int64 department_id = 9 [json_name = "department_id"];
}

// permission.table.comment
message Permission {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // create_time.field.comment
  google.protobuf.Timestamp create_time = 2 [json_name = "create_time"];
  // update_time.field.comment
  google.protobuf.Timestamp update_time = 3 [json_name = "update_time"];
  // create_author.field.comment
  int64 create_author = 4 [json_name = "create_author"];
  // update_author.field.comment
  int64 update_author = 5 [json_name = "update_author"];
  // permission.field.name
  string name = 6 [json_name = "name"];
  // permission.field.keyword
  string keyword = 7 [json_name = "keyword"];
  // permission.field.status
  int32 status = 8 [json_name = "status"];
  // permission.field.description
  string description = 9 [json_name = "description"];
  // permission.field.data_scope
  string data_scope = 10 [json_name = "data_scope"];
  // permission.field.data_rules
  map<string, string> data_rules = 11 [json_name = "data_rules"];
  // permission.field.resource_ids
  repeated int64 resource_ids = 12 [json_name = "resource_ids"];
  // permission.field.resources
  repeated Resource resources = 13 [json_name = "resources"];
  // permission.field.view_ids
  repeated int64 view_ids = 14 [json_name = "view_ids"];
  // permission.field.views
  repeated View views = 15 [json_name = "views"];
}

// user_position.table.comment
message UserPosition {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // field.foreign_key.comment
  int64 user_id = 2 [json_name = "user_id"];
  // field.foreign_key.comment
  int64 position_id = 3 [json_name = "position_id"];
}

// position_permission.table.comment
message PositionPermission {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // position_permission.field.position_id
  int64 position_id = 2 [json_name = "position_id"];
  // position_permission.field.permission_id
  int64 permission_id = 3 [json_name = "permission_id"];
}

// role_permission.table.comment
message RolePermission {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // field.foreign_key.comment
  int64 role_id = 2 [json_name = "role_id"];
  // field.foreign_key.comment
  int64 permission_id = 3 [json_name = "permission_id"];
}

// permission_resource.table.comment
message PermissionResource {
  // ID of the ent.
  // field.primary_key.comment
  int64 id = 1 [json_name = "id"];
  // field.foreign_key.comment
  int64 permission_id = 2 [json_name = "permission_id"];
  // field.foreign_key.comment
  int64 resource_id = 3 [json_name = "resource_id"];
  // permission_resource.field.actions
  string actions = 4 [json_name = "actions"];
}
