version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile # Use the root Dockerfile
      args:
        SERVICE_NAME: gateway # Pass the service name as a build argument
    ports:
      - "8000:8000" # Expose gateway's HTTP port
      - "9000:9000" # Expose gateway's gRPC port
    volumes:
      - .:/app # Mount the entire project directory to enable live reload
    depends_on:
      - auth
      - system

  auth:
    build:
      context: .
      dockerfile: Dockerfile # Use the root Dockerfile
      args:
        SERVICE_NAME: auth # Pass the service name as a build argument
    volumes:
      - .:/app
    # No ports need to be exposed as it's an internal service.

  system:
    build:
      context: .
      dockerfile: Dockerfile # Use the root Dockerfile
      args:
        SERVICE_NAME: system # Pass the service name as a build argument
    volumes:
      - .:/app
    # No ports need to be exposed as it's an internal service.
