// Code generated by protoc-gen-go-bridge. DO NOT EDIT.
// versions:
// - protoc-gen-go-bridge v0.0.2
// - protoc             (unknown)
// source: filemanager/filemanager.proto

package filemanager

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion1
const _ = grpc.SupportPackageIsVersion9

var (
	_ = io.EOF
	_ = status.Errorf
	_ = codes.Unimplemented
)

const FileManagerServiceUploadFileBridgeOperation = "/api.v1.services.filemanager.FileManagerService/UploadFile"
const FileManagerServiceGetFileBridgeOperation = "/api.v1.services.filemanager.FileManagerService/GetFile"
const FileManagerServiceDeleteFileBridgeOperation = "/api.v1.services.filemanager.FileManagerService/DeleteFile"

type FileManagerServiceBridgeServer interface {
	// Uploads a file and creates its metadata.
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Gets file metadata.
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// Deletes a file and its metadata.
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
}

type FileManagerServiceHooker interface {
	FileManagerServiceUploadFileHooker
	FileManagerServiceGetFileHooker
	FileManagerServiceDeleteFileHooker
}

type FileManagerServiceHookedBridger interface {
	FileManagerServiceHooker
	FileManagerServiceBridgeServer
}
type FileManagerServiceUploadFileHooker interface {
	PrepareUploadFile(http.Context, *UploadFileRequest) (context.Context, error)
	CompleteUploadFile(http.Context, *UploadFileRequest, *UploadFileResponse) error
}
type FileManagerServiceGetFileHooker interface {
	PrepareGetFile(http.Context, *GetFileRequest) (context.Context, error)
	CompleteGetFile(http.Context, *GetFileRequest, *GetFileResponse) error
}
type FileManagerServiceDeleteFileHooker interface {
	PrepareDeleteFile(http.Context, *DeleteFileRequest) (context.Context, error)
	CompleteDeleteFile(http.Context, *DeleteFileRequest, *DeleteFileResponse) error
}

func RegisterFileManagerServiceBridgeServer(s *http.Server, srv FileManagerServiceHookedBridger) {
	r := s.Route("/")
	r.POST("/files/upload", _FileManagerService_UploadFile0_Bridge_Handler(srv))
	r.GET("/files/:id", _FileManagerService_GetFile0_Bridge_Handler(srv))
	r.DELETE("/files/:id", _FileManagerService_DeleteFile0_Bridge_Handler(srv))
}

func _FileManagerService_UploadFile0_Bridge_Handler(srv FileManagerServiceHookedBridger) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileManagerServiceUploadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadFile(ctx, req.(*UploadFileRequest))
		})

		newctx, err := srv.PrepareUploadFile(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.CompleteUploadFile(ctx, &in, out.(*UploadFileResponse))
	}
}

func _FileManagerService_GetFile0_Bridge_Handler(srv FileManagerServiceHookedBridger) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileManagerServiceGetFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFile(ctx, req.(*GetFileRequest))
		})

		newctx, err := srv.PrepareGetFile(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.CompleteGetFile(ctx, &in, out.(*GetFileResponse))
	}
}

func _FileManagerService_DeleteFile0_Bridge_Handler(srv FileManagerServiceHookedBridger) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteFileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileManagerServiceDeleteFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteFile(ctx, req.(*DeleteFileRequest))
		})

		newctx, err := srv.PrepareDeleteFile(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.CompleteDeleteFile(ctx, &in, out.(*DeleteFileResponse))
	}
}

// UnimplementedFileManagerServiceHooked must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileManagerServiceHooked struct{}

func (UnimplementedFileManagerServiceHooked) PrepareUploadFile(ctx http.Context, in *UploadFileRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedFileManagerServiceHooked) CompleteUploadFile(ctx http.Context, in *UploadFileRequest, out *UploadFileResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedFileManagerServiceHooked) PrepareGetFile(ctx http.Context, in *GetFileRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedFileManagerServiceHooked) CompleteGetFile(ctx http.Context, in *GetFileRequest, out *GetFileResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedFileManagerServiceHooked) PrepareDeleteFile(ctx http.Context, in *DeleteFileRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedFileManagerServiceHooked) CompleteDeleteFile(ctx http.Context, in *DeleteFileRequest, out *DeleteFileResponse) error {
	return ctx.Result(200, out)
}

func WithFileManagerServiceHook(h FileManagerServiceHooker) func(FileManagerServiceBridgeServer) FileManagerServiceHookedBridger {
	return func(srv FileManagerServiceBridgeServer) FileManagerServiceHookedBridger {
		return FileManagerServiceHookedBridge{FileManagerServiceBridgeServer: srv, FileManagerServiceHooker: h}
	}
}

// FileManagerServiceHookedBridge is a bridge between the HTTP and gRPC implementations of FileManagerService.
// It implements the HTTP and gRPC implementations of FileManagerService.
// It forwards requests and responses between the two implementations.
type FileManagerServiceHookedBridge struct {
	FileManagerServiceBridgeServer
	FileManagerServiceHooker
}

type FileManagerServiceHTTPBridgeImpl struct {
	client FileManagerServiceHTTPClient
}

func NewFileManagerServiceHTTPBridge(client *http.Client) FileManagerServiceHTTPServer {
	return &FileManagerServiceHTTPBridgeImpl{client: NewFileManagerServiceHTTPClient(client)}
}

func (c *FileManagerServiceHTTPBridgeImpl) UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error) {
	return c.client.UploadFile(ctx, in)
}

func (c *FileManagerServiceHTTPBridgeImpl) GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error) {
	return c.client.GetFile(ctx, in)
}

func (c *FileManagerServiceHTTPBridgeImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest) (*DeleteFileResponse, error) {
	return c.client.DeleteFile(ctx, in)
}

type FileManagerServiceBridgeImpl struct {
	client FileManagerServiceClient
}

func NewFileManagerServiceBridge(client grpc.ClientConnInterface) FileManagerServiceServer {
	return &FileManagerServiceBridgeImpl{client: NewFileManagerServiceClient(client)}
}

func (c *FileManagerServiceBridgeImpl) UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error) {
	return c.client.UploadFile(ctx, in)
}

func (c *FileManagerServiceBridgeImpl) GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error) {
	return c.client.GetFile(ctx, in)
}

func (c *FileManagerServiceBridgeImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest) (*DeleteFileResponse, error) {
	return c.client.DeleteFile(ctx, in)
}

func (c *FileManagerServiceBridgeImpl) mustEmbedUnimplementedFileManagerServiceServer() {}

type FileManagerServiceGRPC2HTTPBridgeImpl struct {
	client FileManagerServiceClient
}

func NewFileManagerServiceGRPC2HTTP(client grpc.ClientConnInterface) FileManagerServiceHTTPServer {
	return &FileManagerServiceGRPC2HTTPBridgeImpl{client: NewFileManagerServiceClient(client)}
}

func (c *FileManagerServiceGRPC2HTTPBridgeImpl) UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error) {
	return c.client.UploadFile(ctx, in)
}

func (c *FileManagerServiceGRPC2HTTPBridgeImpl) GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error) {
	return c.client.GetFile(ctx, in)
}

func (c *FileManagerServiceGRPC2HTTPBridgeImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest) (*DeleteFileResponse, error) {
	return c.client.DeleteFile(ctx, in)
}

type FileManagerServiceHTTP2GRPCBridgeImpl struct {
	client FileManagerServiceHTTPClient
}

func NewFileManagerServiceHTTP2GRPC(client *http.Client) FileManagerServiceServer {
	return &FileManagerServiceHTTP2GRPCBridgeImpl{client: NewFileManagerServiceHTTPClient(client)}
}

func (c *FileManagerServiceHTTP2GRPCBridgeImpl) UploadFile(ctx context.Context, in *UploadFileRequest) (*UploadFileResponse, error) {
	return c.client.UploadFile(ctx, in)
}

func (c *FileManagerServiceHTTP2GRPCBridgeImpl) GetFile(ctx context.Context, in *GetFileRequest) (*GetFileResponse, error) {
	return c.client.GetFile(ctx, in)
}

func (c *FileManagerServiceHTTP2GRPCBridgeImpl) DeleteFile(ctx context.Context, in *DeleteFileRequest) (*DeleteFileResponse, error) {
	return c.client.DeleteFile(ctx, in)
}

func (c *FileManagerServiceHTTP2GRPCBridgeImpl) mustEmbedUnimplementedFileManagerServiceServer() {}
