// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: filemanager/filemanager.proto

package filemanager

import (
	_ "github.com/origadmin/contrib/api/gen/go/policy/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	types "origadmin/application/admin/api/v1/services/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,proto3" json:"content_type,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata  *types.FileMetadata    `protobuf:"bytes,1,opt,name=file_metadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetFileMetadata() *types.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type InitiateMultipartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,proto3" json:"content_type,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadRequest) Reset() {
	*x = InitiateMultipartUploadRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadRequest) ProtoMessage() {}

func (x *InitiateMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{2}
}

func (x *InitiateMultipartUploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiateMultipartUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitiateMultipartUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitiateMultipartUploadRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type InitiateMultipartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadResponse) Reset() {
	*x = InitiateMultipartUploadResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadResponse) ProtoMessage() {}

func (x *InitiateMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{3}
}

func (x *InitiateMultipartUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetMultipartUploadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,proto3" json:"upload_id,omitempty"`
	PartNumber    int32                  `protobuf:"varint,2,opt,name=part_number,proto3" json:"part_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipartUploadUrlRequest) Reset() {
	*x = GetMultipartUploadUrlRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipartUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartUploadUrlRequest) ProtoMessage() {}

func (x *GetMultipartUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetMultipartUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{4}
}

func (x *GetMultipartUploadUrlRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *GetMultipartUploadUrlRequest) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

type GetMultipartUploadUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,proto3" json:"upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipartUploadUrlResponse) Reset() {
	*x = GetMultipartUploadUrlResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipartUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipartUploadUrlResponse) ProtoMessage() {}

func (x *GetMultipartUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipartUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetMultipartUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{5}
}

func (x *GetMultipartUploadUrlResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type CompleteMultipartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,proto3" json:"upload_id,omitempty"`
	Parts         []*PartInfo            `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"` // ADDED: For end-to-end verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadRequest) Reset() {
	*x = CompleteMultipartUploadRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadRequest) ProtoMessage() {}

func (x *CompleteMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteMultipartUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *CompleteMultipartUploadRequest) GetParts() []*PartInfo {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CompleteMultipartUploadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type PartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=part_number,proto3" json:"part_number,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	mi := &file_filemanager_filemanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{7}
}

func (x *PartInfo) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *PartInfo) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CompleteMultipartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata  *types.FileMetadata    `protobuf:"bytes,1,opt,name=file_metadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadResponse) Reset() {
	*x = CompleteMultipartUploadResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadResponse) ProtoMessage() {}

func (x *CompleteMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteMultipartUploadResponse) GetFileMetadata() *types.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type AbortMultipartUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartUploadRequest) Reset() {
	*x = AbortMultipartUploadRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartUploadRequest) ProtoMessage() {}

func (x *AbortMultipartUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartUploadRequest.ProtoReflect.Descriptor instead.
func (*AbortMultipartUploadRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{9}
}

func (x *AbortMultipartUploadRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type AbortMultipartUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMultipartUploadResponse) Reset() {
	*x = AbortMultipartUploadResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMultipartUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMultipartUploadResponse) ProtoMessage() {}

func (x *AbortMultipartUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMultipartUploadResponse.ProtoReflect.Descriptor instead.
func (*AbortMultipartUploadResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{10}
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata  *types.FileMetadata    `protobuf:"bytes,1,opt,name=file_metadata,proto3" json:"file_metadata,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=download_url,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileResponse) GetFileMetadata() *types.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

func (x *GetFileResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,proto3" json:"page_token,omitempty"`
	PagingMode    *string                `protobuf:"bytes,4,opt,name=paging_mode,proto3,oneof" json:"paging_mode,omitempty"`
	OnlyCount     bool                   `protobuf:"varint,5,opt,name=only_count,proto3" json:"only_count,omitempty"`
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`
	OwnerId       int64                  `protobuf:"varint,7,opt,name=owner_id,proto3" json:"owner_id,omitempty"`
	Visibility    string                 `protobuf:"bytes,8,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{13}
}

func (x *ListFilesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListFilesRequest) GetPagingMode() string {
	if x != nil && x.PagingMode != nil {
		return *x.PagingMode
	}
	return ""
}

func (x *ListFilesRequest) GetOnlyCount() bool {
	if x != nil {
		return x.OnlyCount
	}
	return false
}

func (x *ListFilesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListFilesRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ListFilesRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Files         []*types.FileMetadata  `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	NextPageToken string                 `protobuf:"bytes,5,opt,name=next_page_token,proto3" json:"next_page_token,omitempty"`
	Extra         *anypb.Any             `protobuf:"bytes,6,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{14}
}

func (x *ListFilesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFilesResponse) GetFiles() []*types.FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFilesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFilesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListFilesResponse) GetExtra() *anypb.Any {
	if x != nil {
		return x.Extra
	}
	return nil
}

type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Visibility    string                 `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFileRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type UpdateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileMetadata  *types.FileMetadata    `protobuf:"bytes,1,opt,name=file_metadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileResponse) Reset() {
	*x = UpdateFileResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileResponse) ProtoMessage() {}

func (x *UpdateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateFileResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateFileResponse) GetFileMetadata() *types.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_filemanager_filemanager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_filemanager_filemanager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filemanager_filemanager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_filemanager_filemanager_proto_rawDescGZIP(), []int{18}
}

var File_filemanager_filemanager_proto protoreflect.FileDescriptor

const file_filemanager_filemanager_proto_rawDesc = "" +
	"\n" +
	"\x1dfilemanager/filemanager.proto\x12\x1bapi.v1.services.filemanager\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x16policy/v1/policy.proto\x1a\x17types/filemanager.proto\"\x7f\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fcontent_type\x18\x03 \x01(\tR\fcontent_type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\"_\n" +
	"\x12UploadFileResponse\x12I\n" +
	"\rfile_metadata\x18\x01 \x01(\v2#.api.v1.services.types.FileMetadataR\rfile_metadata\"\x8c\x01\n" +
	"\x1eInitiateMultipartUploadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\"\n" +
	"\fcontent_type\x18\x03 \x01(\tR\fcontent_type\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\"?\n" +
	"\x1fInitiateMultipartUploadResponse\x12\x1c\n" +
	"\tupload_id\x18\x01 \x01(\tR\tupload_id\"^\n" +
	"\x1cGetMultipartUploadUrlRequest\x12\x1c\n" +
	"\tupload_id\x18\x01 \x01(\tR\tupload_id\x12 \n" +
	"\vpart_number\x18\x02 \x01(\x05R\vpart_number\"?\n" +
	"\x1dGetMultipartUploadUrlResponse\x12\x1e\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\n" +
	"upload_url\"\x93\x01\n" +
	"\x1eCompleteMultipartUploadRequest\x12\x1c\n" +
	"\tupload_id\x18\x01 \x01(\tR\tupload_id\x12;\n" +
	"\x05parts\x18\x02 \x03(\v2%.api.v1.services.filemanager.PartInfoR\x05parts\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"@\n" +
	"\bPartInfo\x12 \n" +
	"\vpart_number\x18\x01 \x01(\x05R\vpart_number\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"l\n" +
	"\x1fCompleteMultipartUploadResponse\x12I\n" +
	"\rfile_metadata\x18\x01 \x01(\v2#.api.v1.services.types.FileMetadataR\rfile_metadata\";\n" +
	"\x1bAbortMultipartUploadRequest\x12\x1c\n" +
	"\tupload_id\x18\x01 \x01(\tR\tupload_id\"\x1e\n" +
	"\x1cAbortMultipartUploadResponse\" \n" +
	"\x0eGetFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x80\x01\n" +
	"\x0fGetFileResponse\x12I\n" +
	"\rfile_metadata\x18\x01 \x01(\v2#.api.v1.services.types.FileMetadataR\rfile_metadata\x12\"\n" +
	"\fdownload_url\x18\x02 \x01(\tR\fdownload_url\"\x91\x02\n" +
	"\x10ListFilesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x02 \x01(\x05R\tpage_size\x12\x1e\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\n" +
	"page_token\x12%\n" +
	"\vpaging_mode\x18\x04 \x01(\tH\x00R\vpaging_mode\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"only_count\x18\x05 \x01(\bR\n" +
	"only_count\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\x1a\n" +
	"\bowner_id\x18\a \x01(\x03R\bowner_id\x12\x1e\n" +
	"\n" +
	"visibility\x18\b \x01(\tR\n" +
	"visibilityB\x0e\n" +
	"\f_paging_mode\"\xfb\x01\n" +
	"\x11ListFilesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x129\n" +
	"\x05files\x18\x02 \x03(\v2#.api.v1.services.types.FileMetadataR\x05files\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x04 \x01(\x05R\tpage_size\x12(\n" +
	"\x0fnext_page_token\x18\x05 \x01(\tR\x0fnext_page_token\x12/\n" +
	"\x05extra\x18\x06 \x01(\v2\x14.google.protobuf.AnyH\x00R\x05extra\x88\x01\x01B\b\n" +
	"\x06_extra\"W\n" +
	"\x11UpdateFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"visibility\x18\x03 \x01(\tR\n" +
	"visibility\"_\n" +
	"\x12UpdateFileResponse\x12I\n" +
	"\rfile_metadata\x18\x01 \x01(\v2#.api.v1.services.types.FileMetadataR\rfile_metadata\"#\n" +
	"\x11DeleteFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteFileResponse2\x97\f\n" +
	"\x12FileManagerService\x12\x8e\x01\n" +
	"\n" +
	"UploadFile\x12..api.v1.services.filemanager.UploadFileRequest\x1a/.api.v1.services.filemanager.UploadFileResponse\"\x1f\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/fm/files\x12\xbf\x01\n" +
	"\x17InitiateMultipartUpload\x12;.api.v1.services.filemanager.InitiateMultipartUploadRequest\x1a<.api.v1.services.filemanager.InitiateMultipartUploadResponse\")\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/fm/files/multipart\x12\xd6\x01\n" +
	"\x15GetMultipartUploadUrl\x129.api.v1.services.filemanager.GetMultipartUploadUrlRequest\x1a:.api.v1.services.filemanager.GetMultipartUploadUrlResponse\"F\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x025\x123/fm/files/multipart/{upload_id}/parts/{part_number}\x12\xd4\x01\n" +
	"\x17CompleteMultipartUpload\x12;.api.v1.services.filemanager.CompleteMultipartUploadRequest\x1a<.api.v1.services.filemanager.CompleteMultipartUploadResponse\">\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02-:\x01*\"(/fm/files/multipart/{upload_id}/complete\x12\xbf\x01\n" +
	"\x14AbortMultipartUpload\x128.api.v1.services.filemanager.AbortMultipartUploadRequest\x1a9.api.v1.services.filemanager.AbortMultipartUploadResponse\"2\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02!*\x1f/fm/files/multipart/{upload_id}\x12\x87\x01\n" +
	"\aGetFile\x12+.api.v1.services.filemanager.GetFileRequest\x1a,.api.v1.services.filemanager.GetFileResponse\"!\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\x10\x12\x0e/fm/files/{id}\x12\x88\x01\n" +
	"\tListFiles\x12-.api.v1.services.filemanager.ListFilesRequest\x1a..api.v1.services.filemanager.ListFilesResponse\"\x1c\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\v\x12\t/fm/files\x12\x93\x01\n" +
	"\n" +
	"UpdateFile\x12..api.v1.services.filemanager.UpdateFileRequest\x1a/.api.v1.services.filemanager.UpdateFileResponse\"$\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/fm/files/{id}\x12\x90\x01\n" +
	"\n" +
	"DeleteFile\x12..api.v1.services.filemanager.DeleteFileRequest\x1a/.api.v1.services.filemanager.DeleteFileResponse\"!\xea\xea\x1b\a\n" +
	"\x05authn\x82\xd3\xe4\x93\x02\x10*\x0e/fm/files/{id}B\x88\x02\n" +
	"\x1fcom.api.v1.services.filemanagerB\x10FilemanagerProtoP\x01ZCorigadmin/application/admin/api/v1/services/filemanager;filemanager\xa2\x02\x04AVSF\xaa\x02\x1bApi.V1.Services.Filemanager\xca\x02\x1bApi\\V1\\Services\\Filemanager\xe2\x02'Api\\V1\\Services\\Filemanager\\GPBMetadata\xea\x02\x1eApi::V1::Services::Filemanagerb\x06proto3"

var (
	file_filemanager_filemanager_proto_rawDescOnce sync.Once
	file_filemanager_filemanager_proto_rawDescData []byte
)

func file_filemanager_filemanager_proto_rawDescGZIP() []byte {
	file_filemanager_filemanager_proto_rawDescOnce.Do(func() {
		file_filemanager_filemanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filemanager_filemanager_proto_rawDesc), len(file_filemanager_filemanager_proto_rawDesc)))
	})
	return file_filemanager_filemanager_proto_rawDescData
}

var file_filemanager_filemanager_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_filemanager_filemanager_proto_goTypes = []any{
	(*UploadFileRequest)(nil),               // 0: api.v1.services.filemanager.UploadFileRequest
	(*UploadFileResponse)(nil),              // 1: api.v1.services.filemanager.UploadFileResponse
	(*InitiateMultipartUploadRequest)(nil),  // 2: api.v1.services.filemanager.InitiateMultipartUploadRequest
	(*InitiateMultipartUploadResponse)(nil), // 3: api.v1.services.filemanager.InitiateMultipartUploadResponse
	(*GetMultipartUploadUrlRequest)(nil),    // 4: api.v1.services.filemanager.GetMultipartUploadUrlRequest
	(*GetMultipartUploadUrlResponse)(nil),   // 5: api.v1.services.filemanager.GetMultipartUploadUrlResponse
	(*CompleteMultipartUploadRequest)(nil),  // 6: api.v1.services.filemanager.CompleteMultipartUploadRequest
	(*PartInfo)(nil),                        // 7: api.v1.services.filemanager.PartInfo
	(*CompleteMultipartUploadResponse)(nil), // 8: api.v1.services.filemanager.CompleteMultipartUploadResponse
	(*AbortMultipartUploadRequest)(nil),     // 9: api.v1.services.filemanager.AbortMultipartUploadRequest
	(*AbortMultipartUploadResponse)(nil),    // 10: api.v1.services.filemanager.AbortMultipartUploadResponse
	(*GetFileRequest)(nil),                  // 11: api.v1.services.filemanager.GetFileRequest
	(*GetFileResponse)(nil),                 // 12: api.v1.services.filemanager.GetFileResponse
	(*ListFilesRequest)(nil),                // 13: api.v1.services.filemanager.ListFilesRequest
	(*ListFilesResponse)(nil),               // 14: api.v1.services.filemanager.ListFilesResponse
	(*UpdateFileRequest)(nil),               // 15: api.v1.services.filemanager.UpdateFileRequest
	(*UpdateFileResponse)(nil),              // 16: api.v1.services.filemanager.UpdateFileResponse
	(*DeleteFileRequest)(nil),               // 17: api.v1.services.filemanager.DeleteFileRequest
	(*DeleteFileResponse)(nil),              // 18: api.v1.services.filemanager.DeleteFileResponse
	(*types.FileMetadata)(nil),              // 19: api.v1.services.types.FileMetadata
	(*anypb.Any)(nil),                       // 20: google.protobuf.Any
}
var file_filemanager_filemanager_proto_depIdxs = []int32{
	19, // 0: api.v1.services.filemanager.UploadFileResponse.file_metadata:type_name -> api.v1.services.types.FileMetadata
	7,  // 1: api.v1.services.filemanager.CompleteMultipartUploadRequest.parts:type_name -> api.v1.services.filemanager.PartInfo
	19, // 2: api.v1.services.filemanager.CompleteMultipartUploadResponse.file_metadata:type_name -> api.v1.services.types.FileMetadata
	19, // 3: api.v1.services.filemanager.GetFileResponse.file_metadata:type_name -> api.v1.services.types.FileMetadata
	19, // 4: api.v1.services.filemanager.ListFilesResponse.files:type_name -> api.v1.services.types.FileMetadata
	20, // 5: api.v1.services.filemanager.ListFilesResponse.extra:type_name -> google.protobuf.Any
	19, // 6: api.v1.services.filemanager.UpdateFileResponse.file_metadata:type_name -> api.v1.services.types.FileMetadata
	0,  // 7: api.v1.services.filemanager.FileManagerService.UploadFile:input_type -> api.v1.services.filemanager.UploadFileRequest
	2,  // 8: api.v1.services.filemanager.FileManagerService.InitiateMultipartUpload:input_type -> api.v1.services.filemanager.InitiateMultipartUploadRequest
	4,  // 9: api.v1.services.filemanager.FileManagerService.GetMultipartUploadUrl:input_type -> api.v1.services.filemanager.GetMultipartUploadUrlRequest
	6,  // 10: api.v1.services.filemanager.FileManagerService.CompleteMultipartUpload:input_type -> api.v1.services.filemanager.CompleteMultipartUploadRequest
	9,  // 11: api.v1.services.filemanager.FileManagerService.AbortMultipartUpload:input_type -> api.v1.services.filemanager.AbortMultipartUploadRequest
	11, // 12: api.v1.services.filemanager.FileManagerService.GetFile:input_type -> api.v1.services.filemanager.GetFileRequest
	13, // 13: api.v1.services.filemanager.FileManagerService.ListFiles:input_type -> api.v1.services.filemanager.ListFilesRequest
	15, // 14: api.v1.services.filemanager.FileManagerService.UpdateFile:input_type -> api.v1.services.filemanager.UpdateFileRequest
	17, // 15: api.v1.services.filemanager.FileManagerService.DeleteFile:input_type -> api.v1.services.filemanager.DeleteFileRequest
	1,  // 16: api.v1.services.filemanager.FileManagerService.UploadFile:output_type -> api.v1.services.filemanager.UploadFileResponse
	3,  // 17: api.v1.services.filemanager.FileManagerService.InitiateMultipartUpload:output_type -> api.v1.services.filemanager.InitiateMultipartUploadResponse
	5,  // 18: api.v1.services.filemanager.FileManagerService.GetMultipartUploadUrl:output_type -> api.v1.services.filemanager.GetMultipartUploadUrlResponse
	8,  // 19: api.v1.services.filemanager.FileManagerService.CompleteMultipartUpload:output_type -> api.v1.services.filemanager.CompleteMultipartUploadResponse
	10, // 20: api.v1.services.filemanager.FileManagerService.AbortMultipartUpload:output_type -> api.v1.services.filemanager.AbortMultipartUploadResponse
	12, // 21: api.v1.services.filemanager.FileManagerService.GetFile:output_type -> api.v1.services.filemanager.GetFileResponse
	14, // 22: api.v1.services.filemanager.FileManagerService.ListFiles:output_type -> api.v1.services.filemanager.ListFilesResponse
	16, // 23: api.v1.services.filemanager.FileManagerService.UpdateFile:output_type -> api.v1.services.filemanager.UpdateFileResponse
	18, // 24: api.v1.services.filemanager.FileManagerService.DeleteFile:output_type -> api.v1.services.filemanager.DeleteFileResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_filemanager_filemanager_proto_init() }
func file_filemanager_filemanager_proto_init() {
	if File_filemanager_filemanager_proto != nil {
		return
	}
	file_filemanager_filemanager_proto_msgTypes[13].OneofWrappers = []any{}
	file_filemanager_filemanager_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filemanager_filemanager_proto_rawDesc), len(file_filemanager_filemanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filemanager_filemanager_proto_goTypes,
		DependencyIndexes: file_filemanager_filemanager_proto_depIdxs,
		MessageInfos:      file_filemanager_filemanager_proto_msgTypes,
	}.Build()
	File_filemanager_filemanager_proto = out.File
	file_filemanager_filemanager_proto_goTypes = nil
	file_filemanager_filemanager_proto_depIdxs = nil
}
