syntax = "proto3";

package api.configs;

import "config/v1/discovery.proto";
import "config/v1/logger.proto";
import "config/v1/service.proto";
import "config/v1/storage.proto";
import "configs/security_config.proto";
import "configs/service.proto";
import "middleware/v1/middleware.proto";
import "validate/validate.proto"; // Updated import statement

option go_package = "origadmin/application/admin/internal/configs";

message EntrySelectorConfig {
  bool global = 2 [json_name = "global"];
  string name = 3 [json_name = "name"];
  string version = 4 [json_name = "version"];
}

//message ServiceServer {
//  string name = 1 [
//    json_name = "name",
//    (validate.rules).string.min_len = 1
//  ];
//  //  Entry entry = 2 [json_name = "entry"]; // 各服务独立入口配置
//  //  repeated config.v1.Service services = 3 [json_name = "services"]; // 服务专用配置
//}

message Bootstrap {
  // name is the application name or service name for used
  string name = 1 [json_name = "name"];
  string version = 2 [json_name = "version"];
  string crypto_type = 3 [json_name = "crypto_type"];
  string mode = 5 [
    json_name = "mode",
    (validate.rules).string = { // Ensure this matches the new import
      in: [
        "singleton",
        "cluster"
      ]
    }
  ];

  bool enable_dynamic_config = 7 [json_name = "enable_dynamic_config"];

  message HealthCheck {
    int32 timeout = 1 [json_name = "timeout"];
    string path = 2 [json_name = "path"];
  }

  // Entry
  message Entry {
    string scheme = 1 [json_name = "scheme"];
    repeated config.v1.Service services = 2 [json_name = "services"];
  }

  string id = 100 [json_name = "id"];
  string environment = 102 [
    json_name = "environment",
    (validate.rules).string = {
      in: [
        "dev",
        "prod"
      ]
    }
  ];

  // 入口服务专属配置
  Entry entry = 103 [json_name = "entry"];

  config.v1.Storage storage = 300 [json_name = "storage"];
  config.v1.Discovery discovery = 400 [json_name = "discovery"];
  middleware.v1.Middleware middleware = 9 [json_name = "middleware"];
  SecurityConfig security = 10 [json_name = "security"];

  HealthCheck health_check = 1003 [json_name = "health_check"];
  config.v1.Logger logger = 1004 [json_name = "logger"];

  ServiceServer server = 1005 [json_name = "server"];
  repeated ServiceClient clients = 1006 [json_name = "clients"];
}

message Settings {
  string crypto_type = 1 [json_name = "crypto_type"];
}
