syntax = "proto3";
package api.configs;

import "config/v1/discovery.proto";
import "config/v1/service.proto";
import "config/v1/storage.proto";
import "middleware/v1/middleware.proto";

option go_package = "origadmin/application/admin/internal/configs";

message ServiceCore {
  string name = 1 [json_name = "name"];
  string version = 2 [json_name = "version"];

  config.v1.Discovery discovery = 3 [json_name = "discovery"];
  repeated config.v1.Storage storages = 4 [json_name = "storages"];
}

message ServiceServer {
  ServiceCore core = 1 [json_name = "core"];
  repeated config.v1.Service services = 200 [json_name = "services"];
  middleware.v1.Middleware middleware = 300 [json_name = "middleware"];
}

message ServiceClient {
  ServiceCore core = 1 [json_name = "core"];
  repeated config.v1.Service services = 200 [json_name = "services"];
  middleware.v1.Middleware middleware = 300 [json_name = "middleware"];
}