syntax = "proto3";
package origadmin.configs.api;

import "config/v1/storage.proto";
import "config/v1/registry.proto";
import "config/v1/service.proto";
import "middleware/v1/middleware.proto";

option go_package = "origadmin/application/admin/internal/configs";

message Server {
  string name = 1 [json_name = "name"];
  string version = 2 [json_name = "version"];

  config.v1.Service service = 200 [json_name = "service"];
  config.v1.Storage storage = 300 [json_name = "storage"];
  config.v1.Registry registry = 400 [json_name = "registry"];
  middleware.v1.Middleware middleware = 9 [json_name = "middleware"];
}
