[[Clients]]
[Clients.Core]
Name = "system"
Version = ""
[Clients.Core.Discovery]
Type = "consul"
ServiceName = "origadmin.service.system.v1"
Debug = false
[Clients.Core.Discovery.Consul]
Address = "${consul_address:127.0.0.1:8500}"
Scheme = "http"
Token = ""
HeartBeat = true
HealthCheck = true
Datacenter = ""
HealthCheckInterval = 30
Timeout = 0
DeregisterCriticalServiceAfter = 0

[[Clients.Services]]
Name = ""
Type = "grpc"
DynamicEndpoint = true
[Clients.Services.Grpc]
Network = "tcp"
Addr = "${grpc_address:0.0.0.0:18000}"
UseTls = false
Timeout = 0
ShutdownTimeout = 0
ReadTimeout = 0
WriteTimeout = 0
IdleTimeout = 0
Endpoint = ""
[Clients.Services.Websocket]
Network = ""
Addr = ""
Path = ""
Codec = ""
Timeout = 0
[Clients.Services.Message]
Type = "none"
Name = ""
[Clients.Services.Message.Mqtt]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Kafka]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rabbitmq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Activemq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nats]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nsq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Pulsar]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Redis]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rocketmq]
Endpoint = ""
Codec = ""
EnableTrace = false
NameServerDomain = ""
AccessKey = ""
SecretKey = ""
SecurityToken = ""
Namespace = ""
InstanceName = ""
GroupName = ""
[Clients.Services.Task]
Type = "none"
Name = ""
[Clients.Services.Task.Asynq]
Endpoint = ""
Password = ""
Db = 0
Location = ""
[Clients.Services.Task.Machinery]
[Clients.Services.Task.Cron]
Addr = ""
[Clients.Services.Middleware]
EnabledMiddlewares = ["logging", "recovery", "tracing", "circuit_breaker", "metadata", "rate_limiter", "metrics", "validator", "jwt", "selector"]
[Clients.Services.Middleware.Metadata]
Enabled = true
Prefix = ""
[Clients.Services.Middleware.RateLimiter]
Enabled = true
Name = "bbr"
Period = 0
XRatelimitLimit = 0
XRatelimitRemaining = 0
XRatelimitReset = 0
RetryAfter = 0
[Clients.Services.Middleware.Metrics]
Enabled = true
[Clients.Services.Middleware.Validator]
Enabled = true
Version = 1
FailFast = true
[Clients.Services.Middleware.Jwt]
Enabled = false
Subject = ""
ClaimType = ""
[Clients.Services.Middleware.Jwt.Config]
SigningMethod = "HS512"
Key = "%VH_C!Vpa$_aK2kOynB&q+x=4$27&Ios"
Key2 = "can empty next version fixed"
AccessTokenLifetime = 900000000000
RefreshTokenLifetime = 259200000000000
Issuer = "localhost"
TokenType = "Bearer"
[Clients.Services.Middleware.Selector]
Enabled = false
Regex = ""
[Clients.Services.Selector]
Version = "v1.0.0"
Builder = "bbr"

[[Clients.Services]]
Name = ""
Type = "http"
DynamicEndpoint = true
[Clients.Services.Http]
Network = "tcp"
Addr = "${http_address:0.0.0.0:18100}"
UseTls = false
Timeout = 0
ShutdownTimeout = 0
ReadTimeout = 0
WriteTimeout = 0
IdleTimeout = 0
Endpoint = ""
[Clients.Services.Websocket]
Network = ""
Addr = ""
Path = ""
Codec = ""
Timeout = 0
[Clients.Services.Message]
Type = "none"
Name = ""
[Clients.Services.Message.Mqtt]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Kafka]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rabbitmq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Activemq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nats]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nsq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Pulsar]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Redis]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rocketmq]
Endpoint = ""
Codec = ""
EnableTrace = false
NameServerDomain = ""
AccessKey = ""
SecretKey = ""
SecurityToken = ""
Namespace = ""
InstanceName = ""
GroupName = ""
[Clients.Services.Task]
Type = "none"
Name = ""
[Clients.Services.Task.Asynq]
Endpoint = ""
Password = ""
Db = 0
Location = ""
[Clients.Services.Task.Machinery]
[Clients.Services.Task.Cron]
Addr = ""
[Clients.Services.Middleware]
EnabledMiddlewares = ["logging", "recovery", "tracing", "circuit_breaker", "metadata", "rate_limiter", "metrics", "validator", "jwt", "selector"]
[Clients.Services.Middleware.Metadata]
Enabled = true
Prefix = ""
[Clients.Services.Middleware.RateLimiter]
Enabled = true
Name = "bbr"
Period = 0
XRatelimitLimit = 0
XRatelimitRemaining = 0
XRatelimitReset = 0
RetryAfter = 0
[Clients.Services.Middleware.Metrics]
Enabled = true
[Clients.Services.Middleware.Validator]
Enabled = true
Version = 1
FailFast = true
[Clients.Services.Middleware.Jwt]
Enabled = false
Subject = ""
ClaimType = ""
[Clients.Services.Middleware.Jwt.Config]
SigningMethod = "HS512"
Key = "%VH_C!Vpa$_aK2kOynB&q+x=4$27&Ios"
Key2 = "can empty next version fixed"
AccessTokenLifetime = 900000000000
RefreshTokenLifetime = 259200000000000
Issuer = "localhost"
TokenType = "Bearer"
[Clients.Services.Middleware.Selector]
Enabled = false
Regex = ""
[Clients.Services.Selector]
Version = "v1.0.0"
Builder = "bbr"

[[Clients]]
[Clients.Core]
Name = "auth"
Version = ""
[Clients.Core.Discovery]
Type = "consul"
ServiceName = "origadmin.service.auth.v1"
Debug = false
[Clients.Core.Discovery.Consul]
Address = "${consul_address:127.0.0.1:8500}"
Scheme = "http"
Token = ""
HeartBeat = true
HealthCheck = true
Datacenter = ""
HealthCheckInterval = 30
Timeout = 0
DeregisterCriticalServiceAfter = 0

[[Clients.Services]]
Name = ""
Type = "grpc"
DynamicEndpoint = true
[Clients.Services.Grpc]
Network = "tcp"
Addr = "${grpc_address:0.0.0.0:18000}"
UseTls = false
Timeout = 0
ShutdownTimeout = 0
ReadTimeout = 0
WriteTimeout = 0
IdleTimeout = 0
Endpoint = ""
[Clients.Services.Websocket]
Network = ""
Addr = ""
Path = ""
Codec = ""
Timeout = 0
[Clients.Services.Message]
Type = "none"
Name = ""
[Clients.Services.Message.Mqtt]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Kafka]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rabbitmq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Activemq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nats]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nsq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Pulsar]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Redis]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rocketmq]
Endpoint = ""
Codec = ""
EnableTrace = false
NameServerDomain = ""
AccessKey = ""
SecretKey = ""
SecurityToken = ""
Namespace = ""
InstanceName = ""
GroupName = ""
[Clients.Services.Task]
Type = "none"
Name = ""
[Clients.Services.Task.Asynq]
Endpoint = ""
Password = ""
Db = 0
Location = ""
[Clients.Services.Task.Machinery]
[Clients.Services.Task.Cron]
Addr = ""
[Clients.Services.Middleware]
EnabledMiddlewares = ["logging", "recovery", "tracing", "circuit_breaker", "metadata", "rate_limiter", "metrics", "validator", "jwt", "selector"]
[Clients.Services.Middleware.Metadata]
Enabled = true
Prefix = ""
[Clients.Services.Middleware.RateLimiter]
Enabled = true
Name = "bbr"
Period = 0
XRatelimitLimit = 0
XRatelimitRemaining = 0
XRatelimitReset = 0
RetryAfter = 0
[Clients.Services.Middleware.Metrics]
Enabled = true
[Clients.Services.Middleware.Validator]
Enabled = true
Version = 1
FailFast = true
[Clients.Services.Middleware.Jwt]
Enabled = false
Subject = ""
ClaimType = ""
[Clients.Services.Middleware.Jwt.Config]
SigningMethod = "HS512"
Key = "%VH_C!Vpa$_aK2kOynB&q+x=4$27&Ios"
Key2 = "can empty next version fixed"
AccessTokenLifetime = 900000000000
RefreshTokenLifetime = 259200000000000
Issuer = "localhost"
TokenType = "Bearer"
[Clients.Services.Middleware.Selector]
Enabled = false
Regex = ""
[Clients.Services.Selector]
Version = "v1.0.0"
Builder = "bbr"

[[Clients.Services]]
Name = ""
Type = "http"
DynamicEndpoint = true
[Clients.Services.Http]
Network = "tcp"
Addr = "${http_address:0.0.0.0:18100}"
UseTls = false
Timeout = 0
ShutdownTimeout = 0
ReadTimeout = 0
WriteTimeout = 0
IdleTimeout = 0
Endpoint = ""
[Clients.Services.Websocket]
Network = ""
Addr = ""
Path = ""
Codec = ""
Timeout = 0
[Clients.Services.Message]
Type = "none"
Name = ""
[Clients.Services.Message.Mqtt]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Kafka]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rabbitmq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Activemq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nats]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Nsq]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Pulsar]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Redis]
Endpoint = ""
Codec = ""
[Clients.Services.Message.Rocketmq]
Endpoint = ""
Codec = ""
EnableTrace = false
NameServerDomain = ""
AccessKey = ""
SecretKey = ""
SecurityToken = ""
Namespace = ""
InstanceName = ""
GroupName = ""
[Clients.Services.Task]
Type = "none"
Name = ""
[Clients.Services.Task.Asynq]
Endpoint = ""
Password = ""
Db = 0
Location = ""
[Clients.Services.Task.Machinery]
[Clients.Services.Task.Cron]
Addr = ""
[Clients.Services.Middleware]
EnabledMiddlewares = ["logging", "recovery", "tracing", "circuit_breaker", "metadata", "rate_limiter", "metrics", "validator", "jwt", "selector"]
[Clients.Services.Middleware.Metadata]
Enabled = true
Prefix = ""
[Clients.Services.Middleware.RateLimiter]
Enabled = true
Name = "bbr"
Period = 0
XRatelimitLimit = 0
XRatelimitRemaining = 0
XRatelimitReset = 0
RetryAfter = 0
[Clients.Services.Middleware.Metrics]
Enabled = true
[Clients.Services.Middleware.Validator]
Enabled = true
Version = 1
FailFast = true
[Clients.Services.Middleware.Jwt]
Enabled = false
Subject = ""
ClaimType = ""
[Clients.Services.Middleware.Jwt.Config]
SigningMethod = "HS512"
Key = "%VH_C!Vpa$_aK2kOynB&q+x=4$27&Ios"
Key2 = "can empty next version fixed"
AccessTokenLifetime = 900000000000
RefreshTokenLifetime = 259200000000000
Issuer = "localhost"
TokenType = "Bearer"
[Clients.Services.Middleware.Selector]
Enabled = false
Regex = ""
[Clients.Services.Selector]
Version = "v1.0.0"
Builder = "bbr"
