clients:
  configs:
    - name: "origadmin.service.identity.client.grpc"
      grpc:
        endpoint: "discovery:///origadmin.service.identity"
        timeout: 3s
        discovery_name: "default_consul"
        middlewares:
          - "propagation"
    - name: "origadmin.service.system.client.grpc"
      grpc:
        endpoint: "discovery:///origadmin.service.system"
        timeout: 3s
        discovery_name: "default_consul"
        middlewares:
          - "propagation"
    - name: "origadmin.service.filemanager.client.grpc"
      grpc:
        endpoint: "discovery:///origadmin.service.filemanager"
        timeout: 5s
        discovery_name: "default_consul"
        middlewares:
          - "propagation"
    - name: "origadmin.service.objectstore.client.grpc"
      grpc:
        endpoint: "discovery:///origadmin.service.objectstore"
        timeout: 5s
        discovery_name: "default_consul"
        middlewares:
          - "propagation"
    - name: "origadmin.service.objectstore.client.http"
      http:
        endpoint: "discovery:///origadmin.service.objectstore"
        discovery_name: "default_consul"
        timeout: 5s
        middlewares:
          - "propagation"
