clients:
  configs:
    - name: "origadmin.service.auth.client.grpc"
      grpc:
#        endpoint: "discovery:///auth"
        timeout: 5s
    - name: "origadmin.service.system.client.grpc"
      grpc:
#        endpoint: "discovery:///system"
        timeout: 5s
