# This file defines reusable middleware configurations.
middlewares:
  configs:
    # Define a middleware instance named "security".
    # The 'type' must match the name we registered in main.go's init() function.
#    - name: security
#      type: security
#      enabled: true
    - name: "logging"
      type: "logging"
      enabled: true
    - name: "tracing"
      type: "tracing"
      enabled: true
    - name: "recovery"
      type: "recovery"
      enabled: true
    #    - name: "validator"
    #      type: "validator"
    #      enabled: false
    - name: "rate_limiter"
      type: "rate_limiter"
      enabled: true
    - name: "metadata"
      type: "metadata"
      enabled: true
