data:
  object_stores:
    default:
      type: local
      local:
        root: ${OBJECTSTORE_BASE_PATH:./tmp/objects}
#         base_url: ${OBJECTSTORE_BASE_URL:http://localhost:8000/api/v1/download/objects}
