# security.yaml
security:
  authn:
    configs:
      - type: jwt
        jwt:
          signing_key: "your-default-secret-key-change-it" # IMPORTANT: Change this in production
          signing_method: "HS256"
          access_token_ttl: 3600s
          refresh_token_ttl: 7200s
  authz:
    configs:
      - type: casbin
        casbin:
          wildcard_item:  "*"
          model_path: "resources/casbin_model.conf"
brokers:
  default:
    type: nats
    url: "nats://localhost:4222/casbin-channel?jetstream=true"
