servers:
  configs:
    # Gateway Service HTTP Server
    - name: "gateway"
      protocol: "http"
      http:
        addr: "0.0.0.0:8000"
        timeout: 5s
        cors:
          allowed_origins:
            - "*"
          allowed_methods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
          allowed_headers:
            - "*"
          allow_credentials: true

    # Auth Service gRPC Server
    - name: "auth"
      protocol: "grpc"
      grpc:
        addr: "0.0.0.0:9081"
        timeout: 5s
    - name: "auth"
      protocol: "http"
      http:
        addr: "0.0.0.0:9082"
        timeout: 5s

    # System Service gRPC Server
    - name: "system"
      protocol: "grpc"
      grpc:
        addr: "0.0.0.0:9001"
        timeout: 5s
    - name: "system"
      protocol: "http"
      http:
        addr: "0.0.0.0:9002"
        timeout: 5s