servers:
  configs:
    # Gateway Service HTTP Server
    - name: "gateway"
      protocol: "http"
      http:
        addr: "0.0.0.0:8000"
        timeout: 5s
        cors:
          allowed_origins:
            - "*"
          allowed_methods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
          allowed_headers:
            - "*"
          allow_credentials: true
        middlewares:
          - recovery
          - tracing
          - logging
          - authn

    # Auth Service gRPC Server
    - name: "auth"
      protocol: "grpc"
      grpc:
        addr: "0.0.0.0:18011"
        timeout: 5s
        middlewares:
          - "recovery"
          - "authz"
    - name: "auth"
      protocol: "http"
      http:
        addr: "0.0.0.0:18012"
        timeout: 5s
        middlewares:
          - "recovery"
          - "authz"
    # System Service gRPC Server
    - name: "system"
      protocol: "grpc"
      grpc:
        addr: "0.0.0.0:18001"
        timeout: 5s
        # Apply middlewares by name. These names must correspond to entries
        # in the middlewares.yaml configuration file.
        middlewares:
          - "recovery"
          - "authz"
    # System Service HTTP Server
    - name: "system"
      protocol: "http"
      http:
        addr: "0.0.0.0:18002"
        timeout: 5s
        # Apply middlewares by name.
        middlewares:
          - "recovery"
          - "authz"
    # Auth Service Watermill Server (for event consumption)
    - name: "auth"
      protocol: "watermill"
      watermill:
        broker:
          type: "nats"
          nats:
            address: "localhost:4222"
            jetstream_enabled: true
            jetstream_stream_name: "system_events"
