// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: types/datastore.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataObject is the model entity for the DataObject schema.
type DataObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the ent.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,proto3" json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=update_time,proto3" json:"update_time,omitempty"`
	// DeleteTime holds the value of the "delete_time" field.
	DeleteTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delete_time,proto3" json:"delete_time,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerId string `protobuf:"bytes,6,opt,name=owner_id,proto3" json:"owner_id,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Payload holds the value of the "payload" field.
	Payload       []byte `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataObject) Reset() {
	*x = DataObject{}
	mi := &file_types_datastore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataObject) ProtoMessage() {}

func (x *DataObject) ProtoReflect() protoreflect.Message {
	mi := &file_types_datastore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataObject.ProtoReflect.Descriptor instead.
func (*DataObject) Descriptor() ([]byte, []int) {
	return file_types_datastore_proto_rawDescGZIP(), []int{0}
}

func (x *DataObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DataObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *DataObject) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

func (x *DataObject) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataObject) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *DataObject) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataObject) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_types_datastore_proto protoreflect.FileDescriptor

const file_types_datastore_proto_rawDesc = "" +
	"\n" +
	"\x15types/datastore.proto\x12\x15api.v1.services.types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x03\n" +
	"\n" +
	"DataObject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcreate_time\x12<\n" +
	"\vupdate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vupdate_time\x12<\n" +
	"\vdelete_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdelete_time\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1a\n" +
	"\bowner_id\x18\x06 \x01(\tR\bowner_id\x12K\n" +
	"\bmetadata\x18\a \x03(\v2/.api.v1.services.types.DataObject.MetadataEntryR\bmetadata\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xdc\x01\n" +
	"\x19com.api.v1.services.typesB\x0eDatastoreProtoP\x01Z7origadmin/application/admin/api/v1/services/types;types\xa2\x02\x04AVST\xaa\x02\x15Api.V1.Services.Types\xca\x02\x15Api\\V1\\Services\\Types\xe2\x02!Api\\V1\\Services\\Types\\GPBMetadata\xea\x02\x18Api::V1::Services::Typesb\x06proto3"

var (
	file_types_datastore_proto_rawDescOnce sync.Once
	file_types_datastore_proto_rawDescData []byte
)

func file_types_datastore_proto_rawDescGZIP() []byte {
	file_types_datastore_proto_rawDescOnce.Do(func() {
		file_types_datastore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_datastore_proto_rawDesc), len(file_types_datastore_proto_rawDesc)))
	})
	return file_types_datastore_proto_rawDescData
}

var file_types_datastore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_datastore_proto_goTypes = []any{
	(*DataObject)(nil),            // 0: api.v1.services.types.DataObject
	nil,                           // 1: api.v1.services.types.DataObject.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_types_datastore_proto_depIdxs = []int32{
	2, // 0: api.v1.services.types.DataObject.create_time:type_name -> google.protobuf.Timestamp
	2, // 1: api.v1.services.types.DataObject.update_time:type_name -> google.protobuf.Timestamp
	2, // 2: api.v1.services.types.DataObject.delete_time:type_name -> google.protobuf.Timestamp
	1, // 3: api.v1.services.types.DataObject.metadata:type_name -> api.v1.services.types.DataObject.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_types_datastore_proto_init() }
func file_types_datastore_proto_init() {
	if File_types_datastore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_datastore_proto_rawDesc), len(file_types_datastore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_datastore_proto_goTypes,
		DependencyIndexes: file_types_datastore_proto_depIdxs,
		MessageInfos:      file_types_datastore_proto_msgTypes,
	}.Build()
	File_types_datastore_proto = out.File
	file_types_datastore_proto_goTypes = nil
	file_types_datastore_proto_depIdxs = nil
}
