syntax = "proto3";

package api.v1.services.upload;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "types/upload.proto";
import "validate/validate.proto";

option go_package = "api/v1/services/upload;upload";
option java_multiple_files = true;
option java_outer_classname = "APIV1ServicesUploadProto";
option java_package = "com.origadmin.api.v1.services.upload";

// The data service definition.
service UploadService {
  rpc ListUpload(ListUploadRequest) returns (ListUploadResponse) {
    option (google.api.http) = {get: "/upload"};
  }
  rpc GetUpload(GetUploadRequest) returns (GetUploadResponse) {
    option (google.api.http) = {get: "/upload/{id}"};
  }
  rpc CreateUpload(CreateUploadRequest) returns (CreateUploadResponse) {
    option (google.api.http) = {
      post: "/upload"
      body: "data"
    };
  }
  rpc UpdateUpload(UpdateUploadRequest) returns (UpdateUploadResponse) {
    option (google.api.http) = {
      put: "/upload/{data.id}"
      body: "data"
    };
  }
  rpc DeleteUpload(DeleteUploadRequest) returns (DeleteUploadResponse) {
    option (google.api.http) = {delete: "/upload/{id}"};
  }
}

// ListUploadRequest is the request for the UploadService.ListUpload method.
message ListUploadRequest {
  // The parent data id, for example, "shelves/shelf1".
  int64 id = 1 [json_name = "id"];
  // The current page number.
  int32 current = 2 [json_name = "current"];
  // The maximum number of items to return.
  int32 page_size = 3 [json_name = "page_size"];
  // The next_page_token value returned from a previous List request, if any.
  string page_token = 4 [json_name = "page_token"];
  // The no_paging is used to disable pagination.
  bool no_paging = 5 [json_name = "no_paging"];
  // The only_count is the query parameter for set only to query the total number
  bool only_count = 6 [json_name = "only_count"];
  // data type
  string type = 7 [json_name = "type"];
}

// ListUploadResponse is the response for the UploadService.ListUpload method.
message ListUploadResponse {
  // The total number of items in the list.
  int32 total_size = 1 [json_name = "total_size"];
  // The paging upload
  repeated api.v1.services.types.DataObject data = 2 [json_name = "data"];
  // The current page number.
  int32 current = 3 [json_name = "current"];
  // The maximum number of items to return.
  int32 page_size = 4 [json_name = "page_size"];
  // Token to retrieve the next page of results, or empty if there are no
  // more results in the list.
  string next_page_token = 5 [json_name = "next_page_token"];
  // Additional information about this response.
  // content to be added without destroying the current data format
  optional google.protobuf.Any extra = 6 [json_name = "extra"];
}

// GetUploadRequest is the request for the UploadService.GetUpload method.
message GetUploadRequest {
  // The field will contain id of the data requested, for example:
  // "shelves/shelf1/upload/data2"
  int64 id = 1 [json_name = "id"];
}

// GetUploadResponse is the response for the UploadService.GetUpload method.
message GetUploadResponse {
  // The field id should match the Noun in the method id.
  api.v1.services.types.DataObject data = 1 [json_name = "data"];
}

// CreateUploadRequest is the request for the UploadService.CreateUpload method.
message CreateUploadRequest {
  // The parent data id where the data is to be created.
  string parent = 1 [json_name = "parent"];
  // The data id to use for this data.
  string data_id = 2 [json_name = "data_id"];
  // The data object to create.
  api.v1.services.types.DataObject data = 3 [json_name = "data"];
}

// CreateUploadResponse is the response for the UploadService.CreateUpload method.
message CreateUploadResponse {
  api.v1.services.types.DataObject data = 1 [json_name = "data"];
}

// UpdateUploadRequest is the request for the UploadService.UpdateUpload method.
message UpdateUploadRequest {
  // The id of the data object to update.
  int64 id = 1 [json_name = "id"];
  // The data object which replaces the data on the server.
  api.v1.services.types.DataObject data = 2 [json_name = "data"];
}

// UpdateUploadResponse is the response for the UploadService.UpdateUpload method.
message UpdateUploadResponse {
  api.v1.services.types.DataObject data = 1 [json_name = "data"];
}

// DeleteUploadRequest is the request for the UploadService.DeleteUpload method.
message DeleteUploadRequest {
  // The data id of the data to be deleted, for example:
  // "shelves/shelf1/upload/data2"
  int64 id = 1 [json_name = "id"];
}

// DeleteUploadResponse is the response for the UploadService.DeleteUpload method.
message DeleteUploadResponse {
  // or Upload data = 1; or google.protobuf.Empty empty = 1;
  google.protobuf.Empty empty = 1;
}
