syntax = "proto3";

package api.v1.services.system;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "policy/v1/policy.proto";
import "types/system.proto";

option go_package = "origadmin/application/admin/api/v1/services/system;system";
option java_multiple_files = true;
option java_outer_classname = "APIServiceSystemPermissionProto";
option java_package = "com.origadmin.api.v1.services.system";
option objc_class_prefix = "APIServiceSystemPermission";

// The login service definition.
service PermissionService {
  rpc ListPermissions(ListPermissionsRequest) returns (ListPermissionsResponse) {
    option (google.api.http) = {get: "/sys/permissions"};
    option (contrib.api.policy.v1.policy) = {name: "jwt-auth"};
  }
  rpc GetPermission(GetPermissionRequest) returns (GetPermissionResponse) {
    option (google.api.http) = {get: "/sys/permissions/{id}"};
    option (contrib.api.policy.v1.policy) = {name: "jwt-auth"};
  }
  rpc CreatePermission(CreatePermissionRequest) returns (CreatePermissionResponse) {
    option (google.api.http) = {
      post: "/sys/permissions"
      body: "*"
    };
    option (contrib.api.policy.v1.policy) = {name: "jwt-auth"};
  }
  rpc UpdatePermission(UpdatePermissionRequest) returns (UpdatePermissionResponse) {
    option (google.api.http) = {
      put: "/sys/permissions/{permission.id}"
      body: "*"
    };
    option (contrib.api.policy.v1.policy) = {name: "jwt-auth"};
  }
  rpc DeletePermission(DeletePermissionRequest) returns (DeletePermissionResponse) {
    option (google.api.http) = {delete: "/sys/permissions/{id}"};
    option (contrib.api.policy.v1.policy) = {name: "jwt-auth"};
  }
}

message ListPermissionsRequest {
  // The page number.
  int32 page = 1 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 2 [json_name = "page_size"];
  // The next_page_token value returned from a previous List request, if any.
  string page_token = 3 [json_name = "page_token"];
  // The paging_mode is used to specify the pagination mode.
  optional string paging_mode = 4 [json_name = "paging_mode"];
  // The only_count is the query parameter for set only to query the total number
  bool only_count = 5 [json_name = "only_count"];
  // The data_scopes is used to query the permission by data scopes.
  repeated string data_scopes = 6 [json_name = "data_scopes"];
  // The keyword is the query parameter for set only to query the permission by keyword
  string keyword = 7 [json_name = "keyword"];
  // The with_resources is the query parameter for set only to query the permission with resources.
  bool with_resources = 10 [json_name = "with_resources"];
  // The with_roles is the query parameter for set only to query the permission with roles.
  bool with_roles = 11 [json_name = "with_roles"];
  // The with_views is the query parameter for set only to query the permission with views.
  bool with_views = 12 [json_name = "with_views"];
}

message ListPermissionsResponse {
  // The total number of items in the list.
  int32 total = 1 [json_name = "total"];
  // The paging permissions
  repeated api.v1.services.types.Permission permissions = 2 [json_name = "permissions"];
  // The page number.
  int32 page = 3 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 4 [json_name = "page_size"];
  // Token to retrieve the next page of results, or empty if there are no
  // more results in the list.
  string next_page_token = 5 [json_name = "next_page_token"];
  // Additional information about this response.
  // content to be added without destroying the page data format
  optional google.protobuf.Any extra = 6 [json_name = "extra"];
}

message GetPermissionRequest {
  // The field will contain id of the resource requested.
  int64 id = 1 [json_name = "id"];
}

message GetPermissionResponse {
  // The permission resource for get.
  api.v1.services.types.Permission permission = 1 [json_name = "permission"];
}

message CreatePermissionRequest {
  // The permission resource to create.
  api.v1.services.types.Permission permission = 1 [json_name = "permission"];
  // For requests: Use this field to set the resources for the permission.
  repeated int64 resource_ids = 2 [json_name = "resource_ids"];
  // For requests: Use this field to set the views for the permission.
  repeated int64 view_ids = 3 [json_name = "view_ids"];
}

message CreatePermissionResponse {
  // The permission resource for create.
  api.v1.services.types.Permission permission = 1 [json_name = "permission"];
}

message UpdatePermissionRequest {
  // The permission resource which replaces the resource on the server.
  api.v1.services.types.Permission permission = 1 [json_name = "permission"];
  // For requests: Use this field to set or replace the list of resources for the permission.
  repeated int64 resource_ids = 2 [json_name = "resource_ids"];
  // For requests: Use this field to set or replace the list of views for the permission.
  repeated int64 view_ids = 3 [json_name = "view_ids"];
}

message UpdatePermissionResponse {
  // The permission resource for update.
  api.v1.services.types.Permission permission = 1 [json_name = "permission"];
}

message DeletePermissionRequest {
  // The resource id of the permission to be deleted.
  int64 id = 1 [json_name = "id"];
}

message DeletePermissionResponse {
  // The permission resource for delete.
  google.protobuf.Empty empty = 1;
}
