syntax = "proto3";

package api.v1.services.system;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "types/system.proto";

option go_package = "origadmin/application/admin/api/v1/services/system;system";
option java_multiple_files = true;
option java_outer_classname = "APIServiceSystemRoleProto";
option java_package = "com.origadmin.api.v1.services.system";
option objc_class_prefix = "APIServiceSystemRole";

// The login service definition.
service RoleService {
  rpc ListRoles(ListRolesRequest) returns (ListRolesResponse) {
    option (google.api.http) = {get: "/sys/roles"};
  }
  rpc GetRole(GetRoleRequest) returns (GetRoleResponse) {
    option (google.api.http) = {get: "/sys/roles/{id}"};
  }
  rpc CreateRole(CreateRoleRequest) returns (CreateRoleResponse) {
    option (google.api.http) = {
      post: "/sys/roles"
      body: "*"
    };
  }
  rpc UpdateRole(UpdateRoleRequest) returns (UpdateRoleResponse) {
    option (google.api.http) = {
      put: "/sys/roles/{role.id}"
      body: "role"
    };
  }
  rpc DeleteRole(DeleteRoleRequest) returns (DeleteRoleResponse) {
    option (google.api.http) = {delete: "/sys/roles/{id}"};
  }
}

message ListRolesRequest {
  // The parent resource id, for example, "shelves/shelf1".
  int64 id = 1 [json_name = "id"];
  // The page number.
  int32 page = 2 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 3 [json_name = "page_size"];
  // The next_page_token value returned from a previous List request, if any.
  string page_token = 4 [json_name = "page_token"];
  // The no_paging is used to disable pagination.
  bool no_paging = 5 [json_name = "no_paging"];
  // The only_count is the query parameter for set only to query the total number
  bool only_count = 6 [json_name = "only_count"];
  // The keyword is the query parameter for set only to query the role by keyword
  string keyword = 7 [json_name = "keyword"];
}

message ListRolesResponse {
  // The total number of items in the list.
  int32 total = 1 [json_name = "total"];
  // The paging roles
  repeated api.v1.services.types.Role roles = 2 [json_name = "roles"];
  // The page number.
  int32 page = 3 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 4 [json_name = "page_size"];
  // Token to retrieve the next page of results, or empty if there are no
  // more results in the list.
  string next_page_token = 5 [json_name = "next_page_token"];
  // Additional information about this response.
  // content to be added without destroying the page data format
  optional google.protobuf.Any extra = 6 [json_name = "extra"];
}

message GetRoleRequest {
  // The field will contain id of the resource requested, for example:
  // "shelves/shelf1/roles/role2"
  int64 id = 1 [json_name = "id"];
}

message GetRoleResponse {
  api.v1.services.types.Role role = 1 [json_name = "role"];
}

message CreateRoleRequest {
  // The parent resource id where the role is to be created.
  string parent = 1 [json_name = "parent"];

  // The role id to use for this role.
  string role_id = 3 [json_name = "role_id"];

  // The role resource to create.
  // The field id should match the Noun in the method id.
  api.v1.services.types.Role role = 2 [json_name = "role"];
}

message CreateRoleResponse {
  api.v1.services.types.Role role = 1 [json_name = "role"];
}

message UpdateRoleRequest {
  // The id of the role resource to update.
  int64 id = 1 [json_name = "id"];
  // The role resource which replaces the resource on the server.
  api.v1.services.types.Role role = 2 [json_name = "role"];
}

message UpdateRoleResponse {
  api.v1.services.types.Role role = 1 [json_name = "role"];
}

message DeleteRoleRequest {
  // The resource id of the role to be deleted, for example:
  // "shelves/shelf1/roles/role2"
  int64 id = 1 [json_name = "id"];
}

message DeleteRoleResponse {
  google.protobuf.Empty empty = 1;
}
