syntax = "proto3";

package api.v1.services.system;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
import "types/system.proto";

option go_package = "origadmin/application/admin/api/v1/services/system;system";
option java_multiple_files = true;
option java_outer_classname = "APIServiceSystemUserProto";
option java_package = "com.origadmin.api.v1.services.system";
option objc_class_prefix = "APIServiceSystemUser";

// The login service definition.
service UserService {
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {get: "/sys/users"};
  }

  rpc ListUserResources(ListUserResourcesRequest) returns (ListUserResourcesResponse) {
    option (google.api.http) = {get: "/sys/users/{id}/resources"};
  }

  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {get: "/sys/users/{id}"};
  }
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/sys/users"
      body: "*"
    };
  }
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse) {
    option (google.api.http) = {
      put: "/sys/users/{user.id}"
      body: "user"
    };
  }
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {
    option (google.api.http) = {delete: "/sys/users/{id}"};
  }
  // UpdateUserStatus Update the status of the user information
  rpc UpdateUserStatus(UpdateUserStatusRequest) returns (UpdateUserStatusResponse) {
    option (google.api.http) = {
      put: "/sys/users/{id}/status"
      body: "*"
    };
  }

  // UpdateUserRoles update the user roles
  rpc UpdateUserRoles(UpdateUserRolesRequest) returns (UpdateUserRolesResponse) {
    option (google.api.http) = {
      put: "/sys/users/{id}/roles"
      body: "*"
    };
  }

  // ResetUserPassword reset the user s password
  rpc ResetUserPassword(ResetUserPasswordRequest) returns (ResetUserPasswordResponse) {
    option (google.api.http) = {
      post: "/sys/users/{id}/password/reset"
      body: "password"
    };
  }
}

message ListUserResourcesRequest {
  int64 id = 1;
}

message ListUserResourcesResponse {
  int32 total = 1 [json_name = "total"];
  repeated api.v1.services.types.Resource resources = 2 [json_name = "resources"];
}

message UpdateUserStatusRequest {
  int64 id = 1;
  int32 status = 2;
  optional api.v1.services.types.User user = 3 [json_name = "user"];
}

message UpdateUserStatusResponse {}

message ResetUserPasswordRequest {
  int64 id = 1;
  string password = 2;
}

message ResetUserPasswordResponse {}

message ListUsersRequest {
  // The parent resource id, for example, "shelves/shelf1".
  int64 id = 1 [json_name = "id"];
  // The page number.
  int32 page = 2 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 3 [json_name = "page_size"];
  // The next_page_token value returned from a previous List request, if any.
  string page_token = 4 [json_name = "page_token"];
  // The no_paging is used to disable pagination.
  bool no_paging = 5 [json_name = "no_paging"];
  // The only_count is the query parameter for set only to query the total number
  bool only_count = 6 [json_name = "only_count"];
  // The title query parameter for set only to query the title
  string keyword = 7 [json_name = "keyword"];
}

message ListUsersResponse {
  // The total number of items in the list.
  int32 total = 1 [json_name = "total"];
  // The paging users
  repeated api.v1.services.types.User users = 2 [json_name = "users"];
  // The page number.
  int32 page = 3 [json_name = "page"];
  // The maximum number of items to return.
  int32 page_size = 4 [json_name = "page_size"];
  // Token to retrieve the next page of results, or empty if there are no
  // more results in the list.
  string next_page_token = 5 [json_name = "next_page_token"];
  // Additional information about this response.
  // content to be added without destroying the page data format
  optional google.protobuf.Any extra = 6 [json_name = "extra"];
}

message GetUserRequest {
  // The field will contain id of the resource requested, for example:
  // "shelves/shelf1/users/user2"
  int64 id = 1;
}

message GetUserResponse {
  api.v1.services.types.User user = 1;
}

message CreateUserRequest {
  // The parent resource id where the user is to be created.
  string parent = 1;
  // The user resource to be created.
  api.v1.services.types.User user = 2;
  // The password to use for this user.
  string password = 3 [json_name = "password"];
  // The user id to use for this user.
  string user_id = 4 [json_name = "user_id"];
  // The user is_system to use for this user.
  bool is_system = 5 [json_name = "is_system"];
  // The random_password is the query parameter for set only to generate a random password
  bool random_password = 6 [json_name = "random_password"];
}

message CreateUserResponse {
  api.v1.services.types.User user = 1;
}

message UpdateUserRequest {
  // The user resource which replaces the resource on the server.
  api.v1.services.types.User user = 1;
  // The user id to use for this user.
  string user_id = 3 [json_name = "user_id"];
  // The user is_system to use for this user.
  bool is_system = 4 [json_name = "is_system"];
  // The random_password is the query parameter for set only to generate a random password
  bool random_password = 2 [json_name = "random_password"];
}

message UpdateUserResponse {
  api.v1.services.types.User user = 1;
}

message DeleteUserRequest {
  // The resource id of the user to be deleted.
  int64 id = 1;
  // The user object, for compatibility.
  optional api.v1.services.types.User user = 2;
}

message DeleteUserResponse {
  google.protobuf.Empty empty = 1;
}

message UpdateUserRolesRequest {
  int64 id = 1;
  api.v1.services.types.User user = 2 [json_name = "user"];
  repeated int64 role_ids = 3 [json_name = "role_ids"];
  //  bool is_add = 5 [json_name = "is_add"];
}

message UpdateUserRolesResponse {
  api.v1.services.types.User user = 1 [json_name = "user"];
}
