// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: conf/pb/conf.proto

package conf

import (
	v1 "github.com/origadmin/runtime/api/gen/go/config/transport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	conf "origadmin/application/admin/conf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap is the top-level configuration structure for the application.
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side configuration for the service itself.
	Servers *v1.Servers `protobuf:"bytes,1,opt,name=servers,proto3" json:"servers,omitempty"`
	// Client-side configurations. The key is the logical name of the downstream service, e.g., "user-service".
	Clients *v1.Clients `protobuf:"bytes,2,opt,name=clients,proto3" json:"clients,omitempty"`
	// Global-level configurations can be placed here.
	SelectorGlobal *SelectorGlobal `protobuf:"bytes,3,opt,name=selector_global,json=selectorGlobal,proto3" json:"selector_global,omitempty"`
	// Captcha feature specific configuration.
	Captcha *Captcha `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	// RootUser feature specific configuration for initial user setup.
	RootUser      *conf.RootUser `protobuf:"bytes,5,opt,name=root_user,json=rootUser,proto3" json:"root_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_pb_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_pb_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_pb_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServers() *v1.Servers {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Bootstrap) GetClients() *v1.Clients {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Bootstrap) GetSelectorGlobal() *SelectorGlobal {
	if x != nil {
		return x.SelectorGlobal
	}
	return nil
}

func (x *Bootstrap) GetCaptcha() *Captcha {
	if x != nil {
		return x.Captcha
	}
	return nil
}

func (x *Bootstrap) GetRootUser() *conf.RootUser {
	if x != nil {
		return x.RootUser
	}
	return nil
}

// SelectorGlobal defines the global selector/load-balancing strategy.
type SelectorGlobal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// builder specifies the global load balancer, e.g., "p2c", "wrr", "random".
	Builder       string `protobuf:"bytes,1,opt,name=builder,proto3" json:"builder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectorGlobal) Reset() {
	*x = SelectorGlobal{}
	mi := &file_conf_pb_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectorGlobal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorGlobal) ProtoMessage() {}

func (x *SelectorGlobal) ProtoReflect() protoreflect.Message {
	mi := &file_conf_pb_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorGlobal.ProtoReflect.Descriptor instead.
func (*SelectorGlobal) Descriptor() ([]byte, []int) {
	return file_conf_pb_conf_proto_rawDescGZIP(), []int{1}
}

func (x *SelectorGlobal) GetBuilder() string {
	if x != nil {
		return x.Builder
	}
	return ""
}

var File_conf_pb_conf_proto protoreflect.FileDescriptor

const file_conf_pb_conf_proto_rawDesc = "" +
	"\n" +
	"\x12conf/pb/conf.proto\x12\x04conf\x1a#config/transport/v1/transport.proto\x1a\x15conf/pb/captcha.proto\x1a\x12conf/pb/root.proto\"\xa8\x02\n" +
	"\tBootstrap\x12B\n" +
	"\aservers\x18\x01 \x01(\v2(.runtime.api.config.transport.v1.ServersR\aservers\x12B\n" +
	"\aclients\x18\x02 \x01(\v2(.runtime.api.config.transport.v1.ClientsR\aclients\x12=\n" +
	"\x0fselector_global\x18\x03 \x01(\v2\x14.conf.SelectorGlobalR\x0eselectorGlobal\x12'\n" +
	"\acaptcha\x18\x04 \x01(\v2\r.conf.CaptchaR\acaptcha\x12+\n" +
	"\troot_user\x18\x05 \x01(\v2\x0e.conf.RootUserR\brootUser\"*\n" +
	"\x0eSelectorGlobal\x12\x18\n" +
	"\abuilder\x18\x01 \x01(\tR\abuilderB0Z.origadmin/application/admin/internal/conf;confb\x06proto3"

var (
	file_conf_pb_conf_proto_rawDescOnce sync.Once
	file_conf_pb_conf_proto_rawDescData []byte
)

func file_conf_pb_conf_proto_rawDescGZIP() []byte {
	file_conf_pb_conf_proto_rawDescOnce.Do(func() {
		file_conf_pb_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_pb_conf_proto_rawDesc), len(file_conf_pb_conf_proto_rawDesc)))
	})
	return file_conf_pb_conf_proto_rawDescData
}

var file_conf_pb_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_conf_pb_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),      // 0: conf.Bootstrap
	(*SelectorGlobal)(nil), // 1: conf.SelectorGlobal
	(*v1.Servers)(nil),     // 2: runtime.api.config.transport.v1.Servers
	(*v1.Clients)(nil),     // 3: runtime.api.config.transport.v1.Clients
	(*Captcha)(nil),        // 4: conf.Captcha
	(*conf.RootUser)(nil),  // 5: conf.RootUser
}
var file_conf_pb_conf_proto_depIdxs = []int32{
	2, // 0: conf.Bootstrap.servers:type_name -> runtime.api.config.transport.v1.Servers
	3, // 1: conf.Bootstrap.clients:type_name -> runtime.api.config.transport.v1.Clients
	1, // 2: conf.Bootstrap.selector_global:type_name -> conf.SelectorGlobal
	4, // 3: conf.Bootstrap.captcha:type_name -> conf.Captcha
	5, // 4: conf.Bootstrap.root_user:type_name -> conf.RootUser
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_conf_pb_conf_proto_init() }
func file_conf_pb_conf_proto_init() {
	if File_conf_pb_conf_proto != nil {
		return
	}
	file_conf_pb_captcha_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_pb_conf_proto_rawDesc), len(file_conf_pb_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_pb_conf_proto_goTypes,
		DependencyIndexes: file_conf_pb_conf_proto_depIdxs,
		MessageInfos:      file_conf_pb_conf_proto_msgTypes,
	}.Build()
	File_conf_pb_conf_proto = out.File
	file_conf_pb_conf_proto_goTypes = nil
	file_conf_pb_conf_proto_depIdxs = nil
}
