syntax = "proto3";

package conf.pb;

option go_package = "origadmin/application/admin/internal/conf/pb;confpb";

// RootUser defines the configuration for the initial administrator user.
// This is used by the seed command.
message RootUser {
  // enabled controls whether the root user initialization task should run.
  bool enabled = 1;
  // username for the root user.
  string username = 2;
  // password for the root user. It is strongly recommended to change this after the first login.
  string password = 3;
  // nickname for the root user.
  optional string nickname = 4;
  // email for the root user.
  optional string email = 5;
}