// Code generated by protoc-gen-go-bridge. DO NOT EDIT.
// versions:
// - protoc-gen-go-bridge unknown
// - protoc             (unknown)
// source: system/menu.proto

package system

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion1
const _ = grpc.SupportPackageIsVersion9

const MenuServiceCreateMenuBridgeOperation = "/api.v1.services.system.MenuService/CreateMenu"
const MenuServiceDeleteMenuBridgeOperation = "/api.v1.services.system.MenuService/DeleteMenu"
const MenuServiceGetMenuBridgeOperation = "/api.v1.services.system.MenuService/GetMenu"
const MenuServiceListMenusBridgeOperation = "/api.v1.services.system.MenuService/ListMenus"
const MenuServiceUpdateMenuBridgeOperation = "/api.v1.services.system.MenuService/UpdateMenu"

type MenuServiceBridger interface {
	CreateMenu(context.Context, *CreateMenuRequest) (*CreateMenuResponse, error)
	DeleteMenu(context.Context, *DeleteMenuRequest) (*DeleteMenuResponse, error)
	GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error)
	ListMenus(context.Context, *ListMenusRequest) (*ListMenusResponse, error)
	UpdateMenu(context.Context, *UpdateMenuRequest) (*UpdateMenuResponse, error)
}

type MenuServiceBridgeHooker interface {
	MenuServiceBridger
	BeforeCreateMenu(http.Context, *CreateMenuRequest) (context.Context, error)
	CreateMenuResult(http.Context, *CreateMenuRequest, *CreateMenuResponse) error
	BeforeDeleteMenu(http.Context, *DeleteMenuRequest) (context.Context, error)
	DeleteMenuResult(http.Context, *DeleteMenuRequest, *DeleteMenuResponse) error
	BeforeGetMenu(http.Context, *GetMenuRequest) (context.Context, error)
	GetMenuResult(http.Context, *GetMenuRequest, *GetMenuResponse) error
	BeforeListMenus(http.Context, *ListMenusRequest) (context.Context, error)
	ListMenusResult(http.Context, *ListMenusRequest, *ListMenusResponse) error
	BeforeUpdateMenu(http.Context, *UpdateMenuRequest) (context.Context, error)
	UpdateMenuResult(http.Context, *UpdateMenuRequest, *UpdateMenuResponse) error
}

func RegisterMenuServiceBridger(s *http.Server, srv MenuServiceBridger) {
	r := s.Route("/")
	hook, ok := srv.(MenuServiceBridgeHooker)
	if !ok {
		hook = UnimplementedMenuServiceBridger{MenuServiceBridger: srv}
	}
	r.GET("/sys/menus", _MenuService_ListMenus0_Bridge_Handler(hook))
	r.GET("/sys/menus/:id", _MenuService_GetMenu0_Bridge_Handler(hook))
	r.POST("/sys/menus", _MenuService_CreateMenu0_Bridge_Handler(hook))
	r.PUT("/sys/menus/:menu.id", _MenuService_UpdateMenu0_Bridge_Handler(hook))
	r.DELETE("/sys/menus/:id", _MenuService_DeleteMenu0_Bridge_Handler(hook))
}

func _MenuService_ListMenus0_Bridge_Handler(srv MenuServiceBridgeHooker) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMenusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceListMenus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMenus(ctx, req.(*ListMenusRequest))
		})

		newctx, err := srv.BeforeListMenus(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.ListMenusResult(ctx, &in, out.(*ListMenusResponse))
	}
}

func _MenuService_GetMenu0_Bridge_Handler(srv MenuServiceBridgeHooker) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMenuRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceGetMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMenu(ctx, req.(*GetMenuRequest))
		})

		newctx, err := srv.BeforeGetMenu(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.GetMenuResult(ctx, &in, out.(*GetMenuResponse))
	}
}

func _MenuService_CreateMenu0_Bridge_Handler(srv MenuServiceBridgeHooker) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMenuRequest
		if err := ctx.Bind(&in.Menu); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceCreateMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMenu(ctx, req.(*CreateMenuRequest))
		})

		newctx, err := srv.BeforeCreateMenu(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.CreateMenuResult(ctx, &in, out.(*CreateMenuResponse))
	}
}

func _MenuService_UpdateMenu0_Bridge_Handler(srv MenuServiceBridgeHooker) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMenuRequest
		if err := ctx.Bind(&in.Menu); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceUpdateMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMenu(ctx, req.(*UpdateMenuRequest))
		})

		newctx, err := srv.BeforeUpdateMenu(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.UpdateMenuResult(ctx, &in, out.(*UpdateMenuResponse))
	}
}

func _MenuService_DeleteMenu0_Bridge_Handler(srv MenuServiceBridgeHooker) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMenuRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuServiceDeleteMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMenu(ctx, req.(*DeleteMenuRequest))
		})

		newctx, err := srv.BeforeDeleteMenu(ctx, &in)
		if err != nil {
			return err
		}
		out, err := h(newctx, &in)
		if err != nil {
			return err
		}
		return srv.DeleteMenuResult(ctx, &in, out.(*DeleteMenuResponse))
	}
}

// UnimplementedMenuServiceBridger must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuServiceBridger struct {
	MenuServiceBridger
}

func (UnimplementedMenuServiceBridger) BeforeCreateMenu(ctx http.Context, in *CreateMenuRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedMenuServiceBridger) CreateMenuResult(ctx http.Context, in *CreateMenuRequest, out *CreateMenuResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedMenuServiceBridger) BeforeDeleteMenu(ctx http.Context, in *DeleteMenuRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedMenuServiceBridger) DeleteMenuResult(ctx http.Context, in *DeleteMenuRequest, out *DeleteMenuResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedMenuServiceBridger) BeforeGetMenu(ctx http.Context, in *GetMenuRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedMenuServiceBridger) GetMenuResult(ctx http.Context, in *GetMenuRequest, out *GetMenuResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedMenuServiceBridger) BeforeListMenus(ctx http.Context, in *ListMenusRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedMenuServiceBridger) ListMenusResult(ctx http.Context, in *ListMenusRequest, out *ListMenusResponse) error {
	return ctx.Result(200, out)
}

func (UnimplementedMenuServiceBridger) BeforeUpdateMenu(ctx http.Context, in *UpdateMenuRequest) (context.Context, error) {
	return ctx, nil
}

func (UnimplementedMenuServiceBridger) UpdateMenuResult(ctx http.Context, in *UpdateMenuRequest, out *UpdateMenuResponse) error {
	return ctx.Result(200, out)
}

type MenuServiceHTTPBridgeImpl struct {
	client MenuServiceHTTPClient
}

func NewMenuServiceHTTPBridge(client *http.Client) MenuServiceHTTPServer {
	return &MenuServiceHTTPBridgeImpl{client: NewMenuServiceHTTPClient(client)}
}

func (c *MenuServiceHTTPBridgeImpl) CreateMenu(ctx context.Context, in *CreateMenuRequest) (*CreateMenuResponse, error) {
	return c.client.CreateMenu(ctx, in)
}

func (c *MenuServiceHTTPBridgeImpl) DeleteMenu(ctx context.Context, in *DeleteMenuRequest) (*DeleteMenuResponse, error) {
	return c.client.DeleteMenu(ctx, in)
}

func (c *MenuServiceHTTPBridgeImpl) GetMenu(ctx context.Context, in *GetMenuRequest) (*GetMenuResponse, error) {
	return c.client.GetMenu(ctx, in)
}

func (c *MenuServiceHTTPBridgeImpl) ListMenus(ctx context.Context, in *ListMenusRequest) (*ListMenusResponse, error) {
	return c.client.ListMenus(ctx, in)
}

func (c *MenuServiceHTTPBridgeImpl) UpdateMenu(ctx context.Context, in *UpdateMenuRequest) (*UpdateMenuResponse, error) {
	return c.client.UpdateMenu(ctx, in)
}

type MenuServiceBridgeImpl struct {
	client MenuServiceClient
}

func NewMenuServiceBridge(client grpc.ClientConnInterface) MenuServiceServer {
	return &MenuServiceBridgeImpl{client: NewMenuServiceClient(client)}
}

func (c *MenuServiceBridgeImpl) CreateMenu(ctx context.Context, in *CreateMenuRequest) (*CreateMenuResponse, error) {
	return c.client.CreateMenu(ctx, in)
}

func (c *MenuServiceBridgeImpl) DeleteMenu(ctx context.Context, in *DeleteMenuRequest) (*DeleteMenuResponse, error) {
	return c.client.DeleteMenu(ctx, in)
}

func (c *MenuServiceBridgeImpl) GetMenu(ctx context.Context, in *GetMenuRequest) (*GetMenuResponse, error) {
	return c.client.GetMenu(ctx, in)
}

func (c *MenuServiceBridgeImpl) ListMenus(ctx context.Context, in *ListMenusRequest) (*ListMenusResponse, error) {
	return c.client.ListMenus(ctx, in)
}

func (c *MenuServiceBridgeImpl) UpdateMenu(ctx context.Context, in *UpdateMenuRequest) (*UpdateMenuResponse, error) {
	return c.client.UpdateMenu(ctx, in)
}

func (c *MenuServiceBridgeImpl) mustEmbedUnimplementedMenuServiceServer() {}
