// Code generated by protoc-gen-go-security. DO NOT EDIT.
// version: 1.0.8

package system

import (
	security "github.com/origadmin/contrib/security"
)

func init() {
	policies := []security.Policy{
		{
			ServiceMethod: "/api.v1.services.system.ViewService/ListViews",
			GatewayPath:   "GET:/sys/views",
			Name:          "authz",
			VersionID:     "e4b8c44fd826aa1fbfa91f365037a329c3617a4389ab77c77f0169bbe3443121",
		},
		{
			ServiceMethod: "/api.v1.services.system.ViewService/GetView",
			GatewayPath:   "GET:/sys/views/{id}",
			Name:          "authz",
			VersionID:     "81a80b79677c987ae8d8558f66535defbdbacb2586b10b76068cf30b866a6210",
		},
		{
			ServiceMethod: "/api.v1.services.system.ViewService/CreateView",
			GatewayPath:   "POST:/sys/views",
			Name:          "authz",
			VersionID:     "76f5db3ed4fbb3a367da3d6a1c9dfaa1f39a3096f0ec30a1880d3d945f814ab0",
		},
		{
			ServiceMethod: "/api.v1.services.system.ViewService/UpdateView",
			GatewayPath:   "PUT:/sys/views/{view.id}",
			Name:          "authz",
			VersionID:     "f69efa596b2ba2802cb2494f711cda59db5670bb4395c47706bdf06efce8d1e5",
		},
		{
			ServiceMethod: "/api.v1.services.system.ViewService/DeleteView",
			GatewayPath:   "DELETE:/sys/views/{id}",
			Name:          "authz",
			VersionID:     "c6936b0b0099191b82b9dcb5577c8013837264a72ec6610509111a62544131f6",
		},
	}

	security.RegisterPolicies(policies)
}
