// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: gateway/gateway.proto

package gateway

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	auth "origadmin/application/admin/api/v1/services/auth"
	system "origadmin/application/admin/api/v1/services/system"
	types "origadmin/application/admin/api/v1/services/types"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\x17api.v1.services.gateway\x1a\x1cgoogle/api/annotations.proto\x1a\x0fauth/auth.proto\x1a\rauth/me.proto\x1a\x11system/user.proto\x1a\x11system/role.proto\x1a\x15system/resource.proto\x1a\x12types/system.proto2\xc6\a\n" +
	"\x0eGatewayService\x12j\n" +
	"\x05Login\x12\".api.v1.services.auth.LoginRequest\x1a#.api.v1.services.auth.LoginResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/login\x12x\n" +
	"\n" +
	"GetCaptcha\x12'.api.v1.services.auth.GetCaptchaRequest\x1a(.api.v1.services.auth.GetCaptchaResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/captcha\x12{\n" +
	"\n" +
	"GetProfile\x12'.api.v1.services.auth.GetProfileRequest\x1a(.api.v1.services.auth.GetProfileResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/me/profile\x12w\n" +
	"\tListUsers\x12(.api.v1.services.system.ListUsersRequest\x1a).api.v1.services.system.ListUsersResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12j\n" +
	"\aGetUser\x12&.api.v1.services.system.GetUserRequest\x1a\x1b.api.v1.services.types.User\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12n\n" +
	"\n" +
	"CreateUser\x12).api.v1.services.system.CreateUserRequest\x1a\x1b.api.v1.services.types.User\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12{\n" +
	"\n" +
	"UpdateUser\x12).api.v1.services.system.UpdateUserRequest\x1a\x1b.api.v1.services.types.User\"%\x82\xd3\xe4\x93\x02\x1f:\x04user\x1a\x17/api/v1/users/{user.id}\x12\x7f\n" +
	"\n" +
	"DeleteUser\x12).api.v1.services.system.DeleteUserRequest\x1a*.api.v1.services.system.DeleteUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}B\xe8\x01\n" +
	"\x1bcom.api.v1.services.gatewayB\fGatewayProtoP\x01Z;origadmin/application/admin/api/v1/services/gateway;gateway\xa2\x02\x04AVSG\xaa\x02\x17Api.V1.Services.Gateway\xca\x02\x17Api\\V1\\Services\\Gateway\xe2\x02#Api\\V1\\Services\\Gateway\\GPBMetadata\xea\x02\x1aApi::V1::Services::Gatewayb\x06proto3"

var file_gateway_gateway_proto_goTypes = []any{
	(*auth.LoginRequest)(nil),         // 0: api.v1.services.auth.LoginRequest
	(*auth.GetCaptchaRequest)(nil),    // 1: api.v1.services.auth.GetCaptchaRequest
	(*auth.GetProfileRequest)(nil),    // 2: api.v1.services.auth.GetProfileRequest
	(*system.ListUsersRequest)(nil),   // 3: api.v1.services.system.ListUsersRequest
	(*system.GetUserRequest)(nil),     // 4: api.v1.services.system.GetUserRequest
	(*system.CreateUserRequest)(nil),  // 5: api.v1.services.system.CreateUserRequest
	(*system.UpdateUserRequest)(nil),  // 6: api.v1.services.system.UpdateUserRequest
	(*system.DeleteUserRequest)(nil),  // 7: api.v1.services.system.DeleteUserRequest
	(*auth.LoginResponse)(nil),        // 8: api.v1.services.auth.LoginResponse
	(*auth.GetCaptchaResponse)(nil),   // 9: api.v1.services.auth.GetCaptchaResponse
	(*auth.GetProfileResponse)(nil),   // 10: api.v1.services.auth.GetProfileResponse
	(*system.ListUsersResponse)(nil),  // 11: api.v1.services.system.ListUsersResponse
	(*types.User)(nil),                // 12: api.v1.services.types.User
	(*system.DeleteUserResponse)(nil), // 13: api.v1.services.system.DeleteUserResponse
}
var file_gateway_gateway_proto_depIdxs = []int32{
	0,  // 0: api.v1.services.gateway.GatewayService.Login:input_type -> api.v1.services.auth.LoginRequest
	1,  // 1: api.v1.services.gateway.GatewayService.GetCaptcha:input_type -> api.v1.services.auth.GetCaptchaRequest
	2,  // 2: api.v1.services.gateway.GatewayService.GetProfile:input_type -> api.v1.services.auth.GetProfileRequest
	3,  // 3: api.v1.services.gateway.GatewayService.ListUsers:input_type -> api.v1.services.system.ListUsersRequest
	4,  // 4: api.v1.services.gateway.GatewayService.GetUser:input_type -> api.v1.services.system.GetUserRequest
	5,  // 5: api.v1.services.gateway.GatewayService.CreateUser:input_type -> api.v1.services.system.CreateUserRequest
	6,  // 6: api.v1.services.gateway.GatewayService.UpdateUser:input_type -> api.v1.services.system.UpdateUserRequest
	7,  // 7: api.v1.services.gateway.GatewayService.DeleteUser:input_type -> api.v1.services.system.DeleteUserRequest
	8,  // 8: api.v1.services.gateway.GatewayService.Login:output_type -> api.v1.services.auth.LoginResponse
	9,  // 9: api.v1.services.gateway.GatewayService.GetCaptcha:output_type -> api.v1.services.auth.GetCaptchaResponse
	10, // 10: api.v1.services.gateway.GatewayService.GetProfile:output_type -> api.v1.services.auth.GetProfileResponse
	11, // 11: api.v1.services.gateway.GatewayService.ListUsers:output_type -> api.v1.services.system.ListUsersResponse
	12, // 12: api.v1.services.gateway.GatewayService.GetUser:output_type -> api.v1.services.types.User
	12, // 13: api.v1.services.gateway.GatewayService.CreateUser:output_type -> api.v1.services.types.User
	12, // 14: api.v1.services.gateway.GatewayService.UpdateUser:output_type -> api.v1.services.types.User
	13, // 15: api.v1.services.gateway.GatewayService.DeleteUser:output_type -> api.v1.services.system.DeleteUserResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
