// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/origadmin/runtime"
	"origadmin/application/admin/api/v1/services/system"
	"origadmin/application/admin/internal/conf/pb"
	"origadmin/application/admin/internal/data"
	"origadmin/application/admin/internal/features/identity/biz"
	"origadmin/application/admin/internal/features/identity/dal"
	"origadmin/application/admin/internal/features/identity/server"
	"origadmin/application/admin/internal/features/identity/service"
	"origadmin/application/admin/internal/helpers/grpcclient"
	"origadmin/application/admin/internal/helpers/providers"
)

import (
	_ "github.com/lib/pq"
	_ "github.com/origadmin/contrib/config/consul"
	_ "github.com/origadmin/contrib/registry/consul"
	_ "github.com/sqlite3ent/sqlite3"
	_ "origadmin/application/admin/internal/data/entity/ent/runtime"
	_ "origadmin/application/admin/internal/helpers/providers"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(app *runtime.App, b *confpb.Bootstrap) (*kratos.App, func(), error) {
	servers := providers.ProvideServers(app)
	database, cleanup, err := data.NewDatabase(app)
	if err != nil {
		return nil, nil, err
	}
	logger := providers.ProvideLogger(app)
	authnRepo := dal.NewAuthnRepo(database, logger)
	crypto, err := providers.ProvideHasher()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authUseCase := biz.NewAuthUseCase(authnRepo, crypto, logger)
	captcha, err := providers.ProvideCaptcha(app)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	captchaUseCase := biz.NewCaptchaUseCase(captcha, logger)
	authenticator, err := providers.ProvideAuthenticator(app)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authService := service.NewAuthService(authUseCase, captchaUseCase, authenticator, logger)
	meRepo := dal.NewMeRepo(database, crypto, logger)
	authzRepo := dal.NewAuthzRepo(database, logger)
	meUseCase := biz.NewMeUseCase(meRepo, authnRepo, authzRepo, crypto, logger)
	meService := service.NewMeService(meUseCase, logger)
	authorizer, err := providers.ProvideAuthorizer(app)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	adminService := service.NewAdminService(authorizer, logger)
	v, err := server.NewServers(app, servers, authService, meService, adminService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kratosApp := NewApp(app, v)
	return kratosApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// NewSystemServiceClient creates a new SystemService client using service discovery.
func NewSystemServiceClient(
	app *runtime.App,
	bootstrap *confpb.Bootstrap,
) (system.UserServiceClient, func(), error) {
	conn, err := grpcclient.NewConn(app, bootstrap, "system")
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		conn.Close()
	}
	return system.NewUserServiceClient(conn), cleanup, nil
}
