[Security]
[Security.Security]
PublicPaths = ["/swagger/*", "/api/v1/health", "/api/v1/health/*", "/api/v1/captcha", "/api/v1/captcha/*", "/api/v1/login", "/api/v1/register", "/api/v1/current/logout", "/api/v1/refresh_token", "/api.v1.services.system.LoginAPI/CaptchaId", "/api.v1.services.system.LoginAPI/CaptchaImage", "/api.v1.services.system.LoginAPI/CaptchaResource", "/api.v1.services.system.LoginAPI/CaptchaResources", "/api.v1.services.system.LoginAPI/Login", "/api.v1.services.system.LoginAPI/Register", "/api.v1.services.system.LoginAPI/Refresh"]
[Security.Security.Authz]
Disabled = false
Type = "casbin"
[Security.Security.Authz.Casbin]
PolicyFile = ""
ModelFile = ""
[Security.Security.Authn]
Disabled = false
Type = "jwt"
[Security.Security.Authn.Jwt]
Algorithm = "HS512"
SigningKey = "%VH_C!Vpa$_aK2kOynB&q+x=4$27&Ios"
OldSigningKey = ""
ExpireTime = 0
RefreshTime = 0
CacheName = ""
