// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/menu"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/resource"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/role"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/rolemenu"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/user"
	"origadmin/application/admin/internal/mods/system/dal/entity/ent/userrole"
)

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *MenuMutation) SetFields(input *Menu, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case menu.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case menu.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case menu.FieldCode:
			m.SetCode(input.Code)
		case menu.FieldName:
			m.SetName(input.Name)
		case menu.FieldDescription:
			m.SetDescription(input.Description)
		case menu.FieldType:
			m.SetType(input.Type)
		case menu.FieldPath:
			m.SetPath(input.Path)
		case menu.FieldStatus:
			m.SetStatus(input.Status)
		case menu.FieldParentID:
			m.SetParentID(input.ParentID)
		case menu.FieldParentPath:
			m.SetParentPath(input.ParentPath)
		case menu.FieldSequence:
			m.SetSequence(input.Sequence)
		case menu.FieldProperties:
			m.SetProperties(input.Properties)
		default:
			return fmt.Errorf("unknown Menu field %s", fields[i])
		}
	}
	return nil
}

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *ResourceMutation) SetFields(input *Resource, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case resource.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case resource.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case resource.FieldMenuID:
			m.SetMenuID(input.MenuID)
		case resource.FieldMethod:
			m.SetMethod(input.Method)
		case resource.FieldPath:
			m.SetPath(input.Path)
		default:
			return fmt.Errorf("unknown Resource field %s", fields[i])
		}
	}
	return nil
}

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *RoleMutation) SetFields(input *Role, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case role.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case role.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case role.FieldCode:
			m.SetCode(input.Code)
		case role.FieldName:
			m.SetName(input.Name)
		case role.FieldDescription:
			m.SetDescription(input.Description)
		case role.FieldSequence:
			m.SetSequence(input.Sequence)
		case role.FieldStatus:
			m.SetStatus(input.Status)
		default:
			return fmt.Errorf("unknown Role field %s", fields[i])
		}
	}
	return nil
}

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *RoleMenuMutation) SetFields(input *RoleMenu, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case rolemenu.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case rolemenu.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case rolemenu.FieldRoleID:
			m.SetRoleID(input.RoleID)
		case rolemenu.FieldMenuID:
			m.SetMenuID(input.MenuID)
		default:
			return fmt.Errorf("unknown RoleMenu field %s", fields[i])
		}
	}
	return nil
}

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *UserMutation) SetFields(input *User, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case user.FieldCreateAuthor:
			m.SetCreateAuthor(input.CreateAuthor)
		case user.FieldUpdateAuthor:
			m.SetUpdateAuthor(input.UpdateAuthor)
		case user.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case user.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case user.FieldIndex:
			m.SetIndex(input.Index)
		case user.FieldDepartment:
			m.SetDepartment(input.Department)
		case user.FieldAllowedIP:
			m.SetAllowedIP(input.AllowedIP)
		case user.FieldUsername:
			m.SetUsername(input.Username)
		case user.FieldName:
			m.SetName(input.Name)
		case user.FieldUserID:
			m.SetUserID(input.UserID)
		case user.FieldAvatar:
			m.SetAvatar(input.Avatar)
		case user.FieldPassword:
			m.SetPassword(input.Password)
		case user.FieldSalt:
			m.SetSalt(input.Salt)
		case user.FieldPhone:
			m.SetPhone(input.Phone)
		case user.FieldEmail:
			m.SetEmail(input.Email)
		case user.FieldRemark:
			m.SetRemark(input.Remark)
		case user.FieldLastLoginTime:
			if !input.LastLoginTime.IsZero() {
				m.SetLastLoginTime(input.LastLoginTime)
			}
		case user.FieldSanctionDate:
			if !input.SanctionDate.IsZero() {
				m.SetSanctionDate(input.SanctionDate)
			}
		case user.FieldStatus:
			m.SetStatus(input.Status)
		case user.FieldManagerID:
			m.SetManagerID(input.ManagerID)
		case user.FieldManager:
			m.SetManager(input.Manager)
		default:
			return fmt.Errorf("unknown User field %s", fields[i])
		}
	}
	return nil
}

// SetFields sets the values of the fields with the given names. It returns an
// error if the field is not defined in the schema, or if the type mismatched the
// field type.
func (m *UserRoleMutation) SetFields(input *UserRole, fields ...string) error {
	for i := range fields {
		switch fields[i] {
		case userrole.FieldCreateTime:
			if !input.CreateTime.IsZero() {
				m.SetCreateTime(input.CreateTime)
			}
		case userrole.FieldUpdateTime:
			if !input.UpdateTime.IsZero() {
				m.SetUpdateTime(input.UpdateTime)
			}
		case userrole.FieldUserID:
			m.SetUserID(input.UserID)
		case userrole.FieldRoleID:
			m.SetRoleID(input.RoleID)
		case userrole.FieldRoleName:
			m.SetRoleName(input.RoleName)
		default:
			return fmt.Errorf("unknown UserRole field %s", fields[i])
		}
	}
	return nil
}
