// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/origadmin/runtime"
	"origadmin/application/admin/internal/conf"
	"origadmin/application/admin/internal/data"
	"origadmin/application/admin/internal/features/system/biz"
	"origadmin/application/admin/internal/features/system/dal"
	"origadmin/application/admin/internal/features/system/server"
	"origadmin/application/admin/internal/features/system/service"
)

import (
	_ "github.com/origadmin/contrib/config/consul"
	_ "github.com/origadmin/contrib/registry/consul"
	_ "github.com/sqlite3ent/sqlite3"
	_ "origadmin/application/admin/internal/data/entity/ent/runtime"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(app *runtime.App, bootstrap *conf.Config) (*kratos.App, func(), error) {
	confpbBootstrap := &bootstrap.Bootstrap
	servers := confpbBootstrap.Servers
	dataData, cleanup, err := data.NewData(app, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	database := data.ProvideDatabase(dataData)
	resourceRepo := dal.NewResourceRepo(database)
	resourceUseCase := biz.NewResourceUseCase(resourceRepo)
	roleRepo := dal.NewRoleRepo(database)
	roleUseCase := biz.NewRoleUseCase(roleRepo)
	userRepo := dal.NewUserRepo(database)
	crypto, err := provideHasher()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userUseCase := biz.NewUserUseCase(userRepo, crypto)
	permissionRepo := dal.NewPermissionRepo(database)
	permissionUseCase := biz.NewPermissionUseCase(permissionRepo)
	viewRepo := dal.NewViewRepo(database)
	viewUseCase := biz.NewViewUseCase(viewRepo)
	systemService := service.New(resourceUseCase, roleUseCase, userUseCase, permissionUseCase, viewUseCase)
	v := provideLogger(app)
	v2, err := server.NewServers(servers, systemService, v)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kratosApp := NewApp(app, v2)
	return kratosApp, func() {
		cleanup()
	}, nil
}
