// Code generated by protoc-gen-go-security. DO NOT EDIT.
// version: 1.1.0

package identity

import (
	security "github.com/origadmin/runtime/security"
)

func init() {
	policies := []security.Policy{
		{
			ServiceMethod: "/api.v1.services.identity.MeService/ListMyViews",
			GatewayPath:   "GET:/me/views",
			Name:          "authn",
			VersionID:     "5aa1370ba4e14cd84174a1ac3d0ffe04cf86f7a6054f77e59ea53c6b81b7524a",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/GetProfile",
			GatewayPath:   "GET:/me/profile",
			Name:          "authn",
			VersionID:     "d0689b30e5e72a626b87656e368c1e16517b7c56a63d5e6ac93467724e1d01b8",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/UpdateProfile",
			GatewayPath:   "PUT:/me/profile",
			Name:          "authn",
			VersionID:     "750b3ebe6edbad79779f8f0f660d9a38246f4849a070781180eef1b6f37ff917",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/UpdatePassword",
			GatewayPath:   "PUT:/me/password",
			Name:          "authn",
			VersionID:     "6c0bffc2fbc753ffdd37f53cd784a5efc6bc6704d7577eeed9c67570ca77d9b0",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/GetUserResources",
			GatewayPath:   "GET:/me/resources",
			Name:          "authn",
			VersionID:     "3e074b81dbc6399f65a89862f2b81ed6d0049af064cdc79b0d23dc7717b0bfda",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/GetUserRoles",
			GatewayPath:   "GET:/me/roles",
			Name:          "authn",
			VersionID:     "fde45c90aeadf1a078fbc34a62c59de18764d736bbb40f8b8ab66bb4cb665321",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/GetUserSettings",
			GatewayPath:   "GET:/me/settings",
			Name:          "authn",
			VersionID:     "344a855aa5489c133372de68ade1924a4dc22a3e75c3e417e3d26675a7949156",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/UpdateSettings",
			GatewayPath:   "PUT:/me/settings",
			Name:          "authn",
			VersionID:     "5479c6b690745ccb33a5ba26ca685aaff0f4a7d9a59a9f20d9e2498b064f7ad7",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/GetUserPreferences",
			GatewayPath:   "GET:/me/preferences",
			Name:          "authn",
			VersionID:     "fa3dc07959ba10a4e8195af42c92ca59722561237d16becebdc2d8fa03e80660",
		},
		{
			ServiceMethod: "/api.v1.services.identity.MeService/UpdatePreferences",
			GatewayPath:   "PUT:/me/preferences",
			Name:          "authn",
			VersionID:     "048501ffb00d32ae56b4942ba2a16e5583336d2ceaf4a2ac5aef3ff66f2d3a77",
		},
	}

	security.RegisterPolicies(policies)
}
