[Storage]
Name = ""
Type = ""
[Storage.Database]
Debug = false
Dialect = "${database_dialect:sqlite3}"
Source = "${database_source:data/admin.db}"
EnableTrace = false
EnableMetrics = false
MaxIdleConnections = 0
MaxOpenConnections = 0
ConnectionMaxLifetime = 0
ConnectionMaxIdleTime = 0
[Storage.Database.Migration]
Enabled = false
Path = ""
Version = ""
Mode = ""
[Storage.Cache]
Driver = "memory"
Name = ""
[Storage.Cache.Memcached]
Addr = ""
Username = ""
Password = ""
MaxIdle = 0
Timeout = 0
[Storage.Cache.Memory]
Size = 0
Capacity = 0
Expiration = 0
CleanupInterval = 0
[Storage.Cache.Redis]
Network = ""
Addr = ""
Password = ""
Db = 0
DialTimeout = 0
ReadTimeout = 0
WriteTimeout = 0
[Storage.Cache.Badger]
Path = ""
SyncWrites = false
ValueLogFileSize = 0
InMemory = false
LogLevel = 0